#!/usr/bin/env node
const crypto = require("crypto");
const https = require("https");
const fs = require("fs");

let versions = [];
const architectures = ["amd64", "arm64", "arm", "ppc64le", "s390x"];
const NODE_VERSION_RE = /^[0-9]+\.[0-9]+\.[0-9]+$/;
const ARCHIVE_SUFFIX_RE = /^(x64|arm64|armv7l|ppc64le|s390x)$/;
const DISTROLESS_ARCH_RE = /^(amd64|arm64|arm|ppc64le|s390x)$/;
const SHA256_RE = /^[0-9a-f]{64}$/;

const nodeVersions = {};

const starlarkString = (value) => {
  return `"${String(value)
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t")}"`;
};

const validateNodeVersion = (version) => {
  if (!NODE_VERSION_RE.test(version)) {
    throw new Error(`Invalid Node.js version: ${version}`);
  }
  return version;
};

const validateArchiveSuffix = (suffix) => {
  if (!ARCHIVE_SUFFIX_RE.test(suffix)) {
    throw new Error(`Invalid Node.js archive suffix: ${suffix}`);
  }
  return suffix;
};

const validateDistrolessArch = (arch) => {
  if (!DISTROLESS_ARCH_RE.test(arch)) {
    throw new Error(`Invalid distroless architecture: ${arch}`);
  }
  return arch;
};

const validateSha256 = (sha256) => {
  if (!SHA256_RE.test(sha256)) {
    throw new Error(`Invalid SHA256 checksum: ${sha256}`);
  }
  return sha256;
};

const calculateChecksum = (url) => {
  return new Promise((resolve, reject) => {
    https
      .get(url, (res) => {
        if (res.statusCode !== 200) {
          res.resume();
          reject(new Error(`Request failed with status code ${res.statusCode}`));
          return;
        }
        const hash = crypto.createHash("sha256");
        res.on("data", (data) => {
          hash.update(data);
        });
        res.on("end", () => {
          resolve(hash.digest("hex"));
        });
      })
      .on("error", (err) => {
        reject(`Error downloading file: ${err.message}`);
      });
  });
};

const fetchChecksums = async () => {
  for (const nodeVersion of versions) {
    validateNodeVersion(nodeVersion);
    const major = parseInt(nodeVersion.split(".")[0]);
    nodeVersions[nodeVersion] = {};
    await Promise.all(
      architectures.map(async (key) => {
        let arch = key;
        if (major > 22 && key === "arm") {
          return;
        }
        if (key === "amd64") {
          arch = "x64";
        } else if (key === "arm") {
          arch = "armv7l";
        }
        validateArchiveSuffix(arch);
        const url = `https://nodejs.org/dist/v${nodeVersion}/node-v${nodeVersion}-linux-${arch}.tar.gz`;
        try {
          const checksum = await calculateChecksum(url);
          nodeVersions[nodeVersion][key] = {
            checksum,
            suffix: arch,
          };
        } catch (error) {
          throw new Error(`Failed to fetch checksum for ${url}: ${error}`);
        }
      })
    );
  }
};

const validateFetchedChecksums = () => {
  for (const nodeVersion of versions) {
    const major = parseInt(nodeVersion.split(".")[0]);
    for (const arch of architectures) {
      if (major > 22 && arch === "arm") {
        continue;
      }
      if (!nodeVersions[nodeVersion] || !nodeVersions[nodeVersion][arch]) {
        throw new Error(
          `Failed to fetch checksum for Node.js version ${nodeVersion} on ${arch}`
        );
      }
    }
  }
};

const main = async () => {
  if (process.argv.length < 3) {
    console.error("Usage: node nodeChecksum.js <nodejs_version>");
    process.exit(1);
  }
  versions = process.argv[2].split(",");
  await fetchChecksums();
  validateFetchedChecksums();

  let nodeArchives = `"node"

BUILD_TMPL = """\\
# GENERATED BY node_archive.bzl
load("@distroless//private/pkg:debian_spdx.bzl", "debian_spdx")
load("@distroless//private/util:merge_providers.bzl", "merge_providers")
load("@distroless//private/util:tar.bzl", "tar")

tar(
    name = "data",
    extension = "tar.gz",
    srcs = glob(
        [
            "output/bin/node",
            "output/LICENSE",
        ],
    ),
    package_dir = "/nodejs",
    strip_prefix = "external/{canonical_name}/output"
)

tar(
    name = "_control",
    extension = "tar.gz",
    srcs = ["control"]
)

debian_spdx(
    name = "spdx",
    control = ":_control",
    data = ":data",
    package_name = "{package_name}",
    spdx_id = "{spdx_id}",
    sha256 = "{sha256}",
    urls = [{urls}]
)

merge_providers(
    name = "{name}",
    srcs = [":data", ":spdx"],
    visibility = ["//visibility:public"],
)
"""

def _impl(rctx):
    rctx.report_progress("Fetching {}".format(rctx.attr.package_name))
    rctx.download_and_extract(
        url = rctx.attr.urls,
        sha256 = rctx.attr.sha256,
        type = rctx.attr.type,
        stripPrefix = rctx.attr.strip_prefix,
        output = "output",
    )
    rctx.template(
        "control",
        rctx.attr.control,
        substitutions = {
            "{{VERSION}}": rctx.attr.version,
            "{{ARCHITECTURE}}": rctx.attr.architecture,
            "{{SHA256}}": rctx.attr.sha256,
        },
    )
    rctx.file(
        "BUILD.bazel",
        content = BUILD_TMPL.format(
            canonical_name = rctx.attr.name,
            name = rctx.attr.name.split("~")[-1],
            package_name = rctx.attr.package_name,
            spdx_id = rctx.attr.name,
            urls = ",".join(['"%s"' % url for url in rctx.attr.urls]),
            sha256 = rctx.attr.sha256,
        ),
    )

node_archive = repository_rule(
    implementation = _impl,
    attrs = {
        "urls": attr.string_list(mandatory = True),
        "sha256": attr.string(mandatory = True),
        "type": attr.string(default = ".tar.gz"),
        "strip_prefix": attr.string(),
        "package_name": attr.string(default = "nodejs"),
        "version": attr.string(mandatory = True),
        "architecture": attr.string(mandatory = True),
        # control is only used to populate the sbom, see https://github.com/GoogleContainerTools/distroless/issues/1373
        # for why writing debian control files to the image is incompatible with scanners.
        "control": attr.label(),
    },
)

_NODE_VERSIONS_TMPL = """\\
"node versions"

# AUTO GENERATED. DO NOT EDIT.
NODEJS_VERSIONS = {versions}
"""

def _node_versions_repo_impl(rctx):
    rctx.file("versions.bzl", _NODE_VERSIONS_TMPL.format(versions = str(rctx.attr.versions)))
    rctx.file("BUILD.bazel", 'exports_files(["versions.bzl"])')

node_versions_repo = repository_rule(
    implementation = _node_versions_repo_impl,
    attrs = {
        "versions": attr.string_dict(),
    },
)

def _node_impl(module_ctx):
    mod = module_ctx.modules[0]

    if len(module_ctx.modules) > 1:
        fail("node.archive should be called only once")
    if not mod.is_root:
        fail("node.archive should be called from root module only.")

    # Node (https://nodejs.org/en/about/releases/)
    # Follow Node's maintenance schedule and support all LTS versions that are not end of life`;

  for (const nodeVersion of versions) {
    const major = parseInt(nodeVersion.split(".")[0]);

    for (const key of architectures) {
      if (major > 22 && key === "arm") {
        continue;
      }
      const arch = nodeVersions[nodeVersion][key];
      const url = `https://nodejs.org/dist/v${nodeVersion}/node-v${nodeVersion}-linux-${arch.suffix}.tar.gz`;
      validateDistrolessArch(key);
      validateArchiveSuffix(arch.suffix);
      validateSha256(arch.checksum);

      nodeArchives += "\n";
      nodeArchives += `
    node_archive(
        name = ${starlarkString(`nodejs${major}_${key}`)},
        sha256 = ${starlarkString(arch.checksum)},
        strip_prefix = ${starlarkString(`node-v${nodeVersion}-linux-${arch.suffix}/`)},
        urls = [${starlarkString(url)}],
        version = ${starlarkString(nodeVersion)},
        architecture = ${starlarkString(key)},
        control = "//nodejs:control",
    )`;
    }

    const testData = `schemaVersion: "2.0.0"
commandTests:
  - name: nodejs
    command: "/nodejs/bin/node"
    args: ["--version"]
    expectedOutput: ["v${nodeVersion}"]
`;

    fs.writeFileSync(`nodejs/testdata/nodejs${major}.yaml`, testData);
  }
  nodeArchives += `

    node_versions_repo(
        name = "node_versions",
        versions = {`;

  for (const nodeVersion of versions) {
    const major = parseInt(nodeVersion.split(".")[0]);
    for (const arch of architectures) {
      if (major > 22 && arch === "arm") {
        continue;
      }
      nodeArchives += `
            "${major}_${arch}": "${nodeVersion}",`;
    }
  }

  nodeArchives += `
        },
    )

    return module_ctx.extension_metadata(
        root_module_direct_deps = [
            "node_versions",`;

  for (const nodeVersion of versions) {
    const major = parseInt(nodeVersion.split(".")[0]);
    for (const arch of architectures) {
      if (major > 22 && arch === "arm") {
        continue;
      }
      nodeArchives += `
            ${starlarkString(`nodejs${major}_${arch}`)},`;
    }
  }

  nodeArchives += `
        ],
        root_module_direct_dev_deps = [],
    )

_archive = tag_class(attrs = {})

node = module_extension(
    implementation = _node_impl,
    tag_classes = {
        "archive": _archive,
    },
)
`;

  // Write output to node_archives.bzl file
  fs.writeFileSync("private/extensions/node.bzl", nodeArchives);
};

if (require.main === module) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}

module.exports = {
  calculateChecksum,
  starlarkString,
  validateArchiveSuffix,
  validateDistrolessArch,
  validateNodeVersion,
  validateSha256,
};
