BUSYBOX_COMMANDS = [
    "usr/bin/[",
    "usr/bin/[[",
    # "sbin/acpid",
    # "sbin/adjtimex",
    "usr/bin/ar",
    "sbin/arp",
    "usr/sbin/arping",
    "bin/ash",
    "usr/bin/awk",
    "usr/bin/basename",
    # "sbin/blockdev",
    # "usr/sbin/brctl",
    "usr/bin/bunzip2",
    "usr/bin/bzcat",
    "usr/bin/bzip2",
    "usr/bin/cal",
    "bin/cat",
    "bin/chgrp",
    "bin/chmod",
    "bin/chown",
    "usr/sbin/chroot",
    # "usr/bin/chvt",
    "usr/bin/clear",
    "usr/bin/cmp",
    "bin/cp",
    "bin/cpio",
    # "bin/cttyhack",
    "usr/bin/cut",
    "bin/date",
    "usr/bin/dc",
    "bin/dd",
    # "usr/bin/deallocvt",
    # "sbin/depmod",
    "sbin/devmem",
    "bin/df",
    "usr/bin/diff",
    "usr/bin/dirname",
    "bin/dmesg",
    "bin/dnsdomainname",
    "usr/bin/dos2unix",
    "usr/bin/du",
    # "bin/dumpkmap",
    # "usr/bin/dumpleases",
    "bin/echo",
    "bin/egrep",
    "usr/bin/env",
    "usr/bin/expand",
    "usr/bin/expr",
    "bin/false",
    "bin/fgrep",
    "usr/bin/find",
    "usr/bin/fold",
    "usr/bin/free",
    # "sbin/freeramdisk",
    # "sbin/fstrim",
    "usr/bin/ftpget",
    "usr/bin/ftpput",
    "bin/getopt",
    # "sbin/getty",
    "bin/grep",
    "usr/bin/groups",
    "bin/gunzip",
    "bin/gzip",
    # "sbin/halt",
    "usr/bin/head",
    "usr/bin/hexdump",
    "usr/bin/hostid",
    "bin/hostname",
    "usr/sbin/httpd",
    # "sbin/hwclock",
    "usr/bin/id",
    "sbin/ifconfig",
    # "sbin/init",
    # "sbin/insmod",
    "bin/ionice",
    "sbin/ip",
    "bin/ipcalc",
    "bin/kill",
    "usr/bin/killall",
    "sbin/klogd",
    # "usr/bin/last",
    "usr/bin/less",
    "bin/ln",
    # "usr/sbin/loadfont",
    # "sbin/loadkmap",
    "usr/bin/logger",
    # "bin/login",
    # "usr/bin/logname",
    # "sbin/logread",
    "sbin/losetup",
    "bin/ls",
    "sbin/lsmod",
    "usr/bin/lzcat",
    "usr/bin/lzma",
    "bin/lzop",
    "usr/bin/lzopcat",
    "usr/bin/md5sum",
    # "sbin/mdev",
    # "usr/bin/microcom",
    "bin/mkdir",
    "usr/bin/mkfifo",
    "bin/mknod",
    # "sbin/mkswap",
    "bin/mktemp",
    # "sbin/modinfo",
    # "sbin/modprobe",
    "bin/more",
    "bin/mount",
    # "bin/mt",
    "bin/mv",
    # "sbin/nameif",
    "usr/bin/nc",
    "bin/netstat",
    "usr/bin/nslookup",
    "usr/bin/od",
    # "usr/bin/openvt",
    "usr/bin/patch",
    "bin/pidof",
    "bin/ping",
    "bin/ping6",
    # "sbin/pivot_root",
    # "sbin/poweroff",
    "usr/bin/printf",
    "bin/ps",
    "bin/pwd",
    # "usr/sbin/rdate",
    "usr/bin/readlink",
    "usr/bin/realpath",
    # "sbin/reboot",
    "usr/bin/renice",
    # "usr/bin/reset",
    "bin/rev",
    "bin/rm",
    "bin/rmdir",
    # "sbin/rmmod",
    "sbin/route",
    "bin/rpm",
    "usr/bin/rpm2cpio",
    "bin/run-parts",
    "bin/sed",
    "usr/bin/seq",
    # "usr/bin/setkeycodes",
    "usr/bin/setsid",
    "bin/sh",
    "usr/bin/sha1sum",
    "usr/bin/sha256sum",
    "usr/bin/sha512sum",
    "bin/sleep",
    "usr/bin/sort",
    "sbin/start-stop-daemon",
    "bin/stat",
    "usr/bin/strings",
    "bin/stty",
    # "sbin/swapoff",
    # "sbin/swapon",
    # "sbin/switch_root",
    "bin/sync",
    "sbin/sysctl",
    "sbin/syslogd",
    "usr/bin/tac",
    "usr/bin/tail",
    "bin/tar",
    "usr/bin/taskset",
    "usr/bin/tee",
    "usr/bin/telnet",
    "usr/bin/test",
    "usr/bin/tftp",
    "usr/bin/time",
    "usr/bin/timeout",
    "usr/bin/top",
    "bin/touch",
    "usr/bin/tr",
    "usr/bin/traceroute",
    "usr/bin/traceroute6",
    "bin/true",
    "usr/bin/tty",
    "sbin/udhcpc",
    # "usr/sbin/udhcpd",
    "bin/umount",
    "bin/uname",
    "bin/uncompress",
    "usr/bin/unexpand",
    "usr/bin/uniq",
    "usr/bin/unix2dos",
    "usr/bin/unlzma",
    "usr/bin/unlzop",
    "usr/bin/unxz",
    "usr/bin/unzip",
    "usr/bin/uptime",
    "bin/usleep",
    "usr/bin/uudecode",
    "usr/bin/uuencode",
    # "sbin/vconfig",
    "bin/vi",
    "bin/watch",
    # "sbin/watchdog",
    "usr/bin/wc",
    "usr/bin/wget",
    "usr/bin/which",
    # "usr/bin/who",
    "usr/bin/whoami",
    "usr/bin/xargs",
    "usr/bin/xz",
    "usr/bin/xzcat",
    "usr/bin/yes",
    "bin/zcat",
]
