# Be sure to break down the "args" of each "step" sufficiently to avoid the
# 4000-character limit of "args" in Cloud Build.

# - Publishing base, cc, and static as latest is handled in a separate internal
#   release process
#
# - Java images are published by java/cloudbuild.yaml to work around the Cloud
#   Build 100-image limit.
#   (https://github.com/GoogleContainerTools/distroless/issues/558)

timeout: 1800s
steps:

- name: gcr.io/cloud-marketplace-containers/google/bazel:3.2.0
  entrypoint: sh
  args:
  - -c
  - |
    #!/bin/sh
    set -o errexit
    set -o xtrace
    bazel build --host_force_python=PY2 //package_manager:dpkg_parser.par

    bazel run --host_force_python=PY2 //base:static_debian9
    bazel run --host_force_python=PY2 //base:static_debian10
    bazel run --host_force_python=PY2 //base:static_nonroot_debian9
    bazel run --host_force_python=PY2 //base:static_nonroot_debian10
    bazel run --host_force_python=PY2 //base:base_debian9
    bazel run --host_force_python=PY2 //base:base_debian10
    bazel run --host_force_python=PY2 //base:base_nonroot_debian9
    bazel run --host_force_python=PY2 //base:base_nonroot_debian10
    bazel run --host_force_python=PY2 //base:debug_debian9
    bazel run --host_force_python=PY2 //base:debug_debian10
    bazel run --host_force_python=PY2 //base:debug_nonroot_debian9
    bazel run --host_force_python=PY2 //base:debug_nonroot_debian10

    bazel run --host_force_python=PY2 //cc:cc_debian9
    bazel run --host_force_python=PY2 //cc:cc_debian10
    bazel run --host_force_python=PY2 //cc:debug_debian9
    bazel run --host_force_python=PY2 //cc:debug_debian10
- name: gcr.io/cloud-builders/docker
  entrypoint: sh
  args:
  - -c
  - |
    #!/bin/sh
    set -o errexit
    set -o xtrace
    docker tag bazel/base:static_debian9          gcr.io/$PROJECT_ID/static:${COMMIT_SHA}
    docker tag bazel/base:static_debian9          gcr.io/$PROJECT_ID/static-debian9:${COMMIT_SHA}
    docker tag bazel/base:static_debian10         gcr.io/$PROJECT_ID/static-debian10:${COMMIT_SHA}
    docker tag bazel/base:static_nonroot_debian9  gcr.io/$PROJECT_ID/static:nonroot
    docker tag bazel/base:static_nonroot_debian9  gcr.io/$PROJECT_ID/static-debian9:nonroot
    docker tag bazel/base:static_nonroot_debian10 gcr.io/$PROJECT_ID/static-debian10:nonroot
    docker tag bazel/base:base_debian9            gcr.io/$PROJECT_ID/base:${COMMIT_SHA}
    docker tag bazel/base:base_debian9            gcr.io/$PROJECT_ID/base-debian9:${COMMIT_SHA}
    docker tag bazel/base:base_debian10           gcr.io/$PROJECT_ID/base-debian10:${COMMIT_SHA}
    docker tag bazel/base:base_nonroot_debian9    gcr.io/$PROJECT_ID/base:nonroot
    docker tag bazel/base:base_nonroot_debian9    gcr.io/$PROJECT_ID/base-debian9:nonroot
    docker tag bazel/base:base_nonroot_debian10   gcr.io/$PROJECT_ID/base-debian10:nonroot
    docker tag bazel/base:debug_debian9           gcr.io/$PROJECT_ID/base:debug
    docker tag bazel/base:debug_debian9           gcr.io/$PROJECT_ID/base-debian9:debug
    docker tag bazel/base:debug_debian10          gcr.io/$PROJECT_ID/base-debian10:debug
    docker tag bazel/base:debug_nonroot_debian9   gcr.io/$PROJECT_ID/base:debug-nonroot
    docker tag bazel/base:debug_nonroot_debian9   gcr.io/$PROJECT_ID/base-debian9:debug-nonroot
    docker tag bazel/base:debug_nonroot_debian10  gcr.io/$PROJECT_ID/base-debian10:debug-nonroot

    docker tag bazel/cc:cc_debian9     gcr.io/$PROJECT_ID/cc:${COMMIT_SHA}
    docker tag bazel/cc:cc_debian9     gcr.io/$PROJECT_ID/cc-debian9:${COMMIT_SHA}
    docker tag bazel/cc:cc_debian10    gcr.io/$PROJECT_ID/cc-debian10:${COMMIT_SHA}
    docker tag bazel/cc:debug_debian9  gcr.io/$PROJECT_ID/cc:debug
    docker tag bazel/cc:debug_debian9  gcr.io/$PROJECT_ID/cc-debian9:debug
    docker tag bazel/cc:debug_debian10 gcr.io/$PROJECT_ID/cc-debian10:debug

- name: gcr.io/cloud-marketplace-containers/google/bazel:3.2.0
  entrypoint: sh
  args:
  - -c
  - |
    #!/bin/sh
    set -o errexit
    set -o xtrace
    bazel run --host_force_python=PY2 //experimental/python3:python3_debian9
    bazel run --host_force_python=PY2 //experimental/python3:python3_debian10
    bazel run --host_force_python=PY2 //experimental/python3:python3_nonroot_debian9
    bazel run --host_force_python=PY2 //experimental/python3:python3_nonroot_debian10
    bazel run --host_force_python=PY2 //experimental/python3:debug_debian9
    bazel run --host_force_python=PY2 //experimental/python3:debug_debian10
    bazel run --host_force_python=PY2 //experimental/python3:debug_nonroot_debian9
    bazel run --host_force_python=PY2 //experimental/python3:debug_nonroot_debian10

    bazel run --host_force_python=PY2 //experimental/python2.7:python27_debian9
    bazel run --host_force_python=PY2 //experimental/python2.7:python27_debian10
    bazel run --host_force_python=PY2 //experimental/python2.7:debug_debian9
    bazel run --host_force_python=PY2 //experimental/python2.7:debug_debian10

    bazel run --host_force_python=PY2 //experimental/nodejs:nodejs10
    bazel run --host_force_python=PY2 //experimental/nodejs:nodejs10_debug
    bazel run --host_force_python=PY2 //experimental/nodejs:nodejs12
    bazel run --host_force_python=PY2 //experimental/nodejs:nodejs12_debug
    bazel run --host_force_python=PY2 //experimental/nodejs:nodejs14
    bazel run --host_force_python=PY2 //experimental/nodejs:nodejs14_debug
- name: gcr.io/cloud-builders/docker
  entrypoint: sh
  args:
  - -c
  - |
    #!/bin/sh
    set -o errexit
    set -o xtrace
    docker tag bazel/experimental/python3:python3_debian9          gcr.io/$PROJECT_ID/python3:latest
    docker tag bazel/experimental/python3:python3_debian9          gcr.io/$PROJECT_ID/python3-debian9:latest
    docker tag bazel/experimental/python3:python3_debian10         gcr.io/$PROJECT_ID/python3-debian10:latest
    docker tag bazel/experimental/python3:python3_nonroot_debian9  gcr.io/$PROJECT_ID/python3:nonroot
    docker tag bazel/experimental/python3:python3_nonroot_debian9  gcr.io/$PROJECT_ID/python3-debian9:nonroot
    docker tag bazel/experimental/python3:python3_nonroot_debian10 gcr.io/$PROJECT_ID/python3-debian10:nonroot
    docker tag bazel/experimental/python3:debug_debian9            gcr.io/$PROJECT_ID/python3:debug
    docker tag bazel/experimental/python3:debug_debian9            gcr.io/$PROJECT_ID/python3-debian9:debug
    docker tag bazel/experimental/python3:debug_debian10           gcr.io/$PROJECT_ID/python3-debian10:debug
    docker tag bazel/experimental/python3:debug_nonroot_debian9    gcr.io/$PROJECT_ID/python3:debug-nonroot
    docker tag bazel/experimental/python3:debug_nonroot_debian9    gcr.io/$PROJECT_ID/python3-debian9:debug-nonroot
    docker tag bazel/experimental/python3:debug_nonroot_debian10   gcr.io/$PROJECT_ID/python3-debian10:debug-nonroot

    docker tag bazel/experimental/python2.7:python27_debian9  gcr.io/$PROJECT_ID/python2.7:latest
    docker tag bazel/experimental/python2.7:python27_debian9  gcr.io/$PROJECT_ID/python2.7-debian9:latest
    docker tag bazel/experimental/python2.7:python27_debian10 gcr.io/$PROJECT_ID/python2.7-debian10:latest
    docker tag bazel/experimental/python2.7:debug_debian9     gcr.io/$PROJECT_ID/python2.7:debug
    docker tag bazel/experimental/python2.7:debug_debian9     gcr.io/$PROJECT_ID/python2.7-debian9:debug
    docker tag bazel/experimental/python2.7:debug_debian10    gcr.io/$PROJECT_ID/python2.7-debian10:debug

    docker tag bazel/experimental/nodejs:nodejs10 gcr.io/$PROJECT_ID/nodejs:latest
    docker tag bazel/experimental/nodejs:nodejs10 gcr.io/$PROJECT_ID/nodejs:10
    docker tag bazel/experimental/nodejs:nodejs12 gcr.io/$PROJECT_ID/nodejs:12
    docker tag bazel/experimental/nodejs:nodejs14 gcr.io/$PROJECT_ID/nodejs:14
    docker tag bazel/experimental/nodejs:nodejs10_debug gcr.io/$PROJECT_ID/nodejs:debug
    docker tag bazel/experimental/nodejs:nodejs10_debug gcr.io/$PROJECT_ID/nodejs:10-debug
    docker tag bazel/experimental/nodejs:nodejs12_debug gcr.io/$PROJECT_ID/nodejs:12-debug
    docker tag bazel/experimental/nodejs:nodejs14_debug gcr.io/$PROJECT_ID/nodejs:14-debug

- name: gcr.io/cloud-marketplace-containers/google/bazel:3.2.0
  entrypoint: sh
  args:
  - -c
  - |
    #!/bin/sh
    set -o errexit
    set -o xtrace
    bazel run --host_force_python=PY2 //experimental/dotnet:dotnet_debian9
    bazel run --host_force_python=PY2 //experimental/dotnet:dotnet_debian10
    bazel run --host_force_python=PY2 //experimental/dotnet:dotnet_core_aspnet_debian9
    bazel run --host_force_python=PY2 //experimental/dotnet:dotnet_core_runtime_debian9
    bazel run --host_force_python=PY2 //experimental/dotnet:dotnet_core_sdk_debian9

    bazel run --host_force_python=PY2 //experimental/dotnet:dotnet_debug_debian9
    bazel run --host_force_python=PY2 //experimental/dotnet:dotnet_debug_debian10
    bazel run --host_force_python=PY2 //experimental/dotnet:dotnet_core_aspnet_debug_debian9
    bazel run --host_force_python=PY2 //experimental/dotnet:dotnet_core_runtime_debug_debian9
    bazel run --host_force_python=PY2 //experimental/dotnet:dotnet_core_sdk_debug_debian9
- name: gcr.io/cloud-builders/docker
  entrypoint: sh
  args:
  - -c
  - |
    #!/bin/sh
    set -o errexit
    set -o xtrace
    docker tag bazel/experimental/dotnet:dotnet_debian9                    gcr.io/$PROJECT_ID/dotnet:latest
    docker tag bazel/experimental/dotnet:dotnet_debian9                    gcr.io/$PROJECT_ID/dotnet-debian9:latest
    docker tag bazel/experimental/dotnet:dotnet_debian10                   gcr.io/$PROJECT_ID/dotnet-debian10:latest
    docker tag bazel/experimental/dotnet:dotnet_debug_debian9              gcr.io/$PROJECT_ID/dotnet:debug
    docker tag bazel/experimental/dotnet:dotnet_debug_debian9              gcr.io/$PROJECT_ID/dotnet-debian9:debug
    docker tag bazel/experimental/dotnet:dotnet_debug_debian10             gcr.io/$PROJECT_ID/dotnet-debian10:debug

    docker tag bazel/experimental/dotnet:dotnet_core_aspnet_debian9        gcr.io/$PROJECT_ID/dotnet/core/aspnet:latest
    docker tag bazel/experimental/dotnet:dotnet_core_aspnet_debian9        gcr.io/$PROJECT_ID/dotnet/core/aspnet:3.1
    docker tag bazel/experimental/dotnet:dotnet_core_aspnet_debug_debian9  gcr.io/$PROJECT_ID/dotnet/core/aspnet:debug
    docker tag bazel/experimental/dotnet:dotnet_core_runtime_debian9       gcr.io/$PROJECT_ID/dotnet/core/runtime:latest
    docker tag bazel/experimental/dotnet:dotnet_core_runtime_debian9       gcr.io/$PROJECT_ID/dotnet/core/runtime:3.1
    docker tag bazel/experimental/dotnet:dotnet_core_runtime_debug_debian9 gcr.io/$PROJECT_ID/dotnet/core/runtime:debug
    docker tag bazel/experimental/dotnet:dotnet_core_sdk_debian9           gcr.io/$PROJECT_ID/dotnet/core/sdk:latest
    docker tag bazel/experimental/dotnet:dotnet_core_sdk_debian9           gcr.io/$PROJECT_ID/dotnet/core/sdk:3.1
    docker tag bazel/experimental/dotnet:dotnet_core_sdk_debug_debian9     gcr.io/$PROJECT_ID/dotnet/core/sdk:debug

images:
  - 'gcr.io/$PROJECT_ID/static:${COMMIT_SHA}'
  - 'gcr.io/$PROJECT_ID/static:nonroot'
  - 'gcr.io/$PROJECT_ID/static-debian9:${COMMIT_SHA}'
  - 'gcr.io/$PROJECT_ID/static-debian9:nonroot'
  - 'gcr.io/$PROJECT_ID/static-debian10:${COMMIT_SHA}'
  - 'gcr.io/$PROJECT_ID/static-debian10:nonroot'
  - 'gcr.io/$PROJECT_ID/base:${COMMIT_SHA}'
  - 'gcr.io/$PROJECT_ID/base:nonroot'
  - 'gcr.io/$PROJECT_ID/base:debug'
  - 'gcr.io/$PROJECT_ID/base:debug-nonroot'
  - 'gcr.io/$PROJECT_ID/base-debian9:${COMMIT_SHA}'
  - 'gcr.io/$PROJECT_ID/base-debian9:nonroot'
  - 'gcr.io/$PROJECT_ID/base-debian9:debug'
  - 'gcr.io/$PROJECT_ID/base-debian9:debug-nonroot'
  - 'gcr.io/$PROJECT_ID/base-debian10:${COMMIT_SHA}'
  - 'gcr.io/$PROJECT_ID/base-debian10:nonroot'
  - 'gcr.io/$PROJECT_ID/base-debian10:debug'
  - 'gcr.io/$PROJECT_ID/base-debian10:debug-nonroot'
  - 'gcr.io/$PROJECT_ID/cc:${COMMIT_SHA}'
  - 'gcr.io/$PROJECT_ID/cc:debug'
  - 'gcr.io/$PROJECT_ID/cc-debian9:${COMMIT_SHA}'
  - 'gcr.io/$PROJECT_ID/cc-debian9:debug'
  - 'gcr.io/$PROJECT_ID/cc-debian10:${COMMIT_SHA}'
  - 'gcr.io/$PROJECT_ID/cc-debian10:debug'
  - 'gcr.io/$PROJECT_ID/python3:latest'
  - 'gcr.io/$PROJECT_ID/python3:nonroot'
  - 'gcr.io/$PROJECT_ID/python3:debug'
  - 'gcr.io/$PROJECT_ID/python3:debug-nonroot'
  - 'gcr.io/$PROJECT_ID/python3-debian9:latest'
  - 'gcr.io/$PROJECT_ID/python3-debian9:nonroot'
  - 'gcr.io/$PROJECT_ID/python3-debian9:debug'
  - 'gcr.io/$PROJECT_ID/python3-debian9:debug-nonroot'
  - 'gcr.io/$PROJECT_ID/python3-debian10:latest'
  - 'gcr.io/$PROJECT_ID/python3-debian10:nonroot'
  - 'gcr.io/$PROJECT_ID/python3-debian10:debug'
  - 'gcr.io/$PROJECT_ID/python3-debian10:debug-nonroot'
  - 'gcr.io/$PROJECT_ID/python2.7:latest'
  - 'gcr.io/$PROJECT_ID/python2.7:debug'
  - 'gcr.io/$PROJECT_ID/python2.7-debian9:latest'
  - 'gcr.io/$PROJECT_ID/python2.7-debian9:debug'
  - 'gcr.io/$PROJECT_ID/python2.7-debian10:latest'
  - 'gcr.io/$PROJECT_ID/python2.7-debian10:debug'
  - 'gcr.io/$PROJECT_ID/nodejs:latest'
  - 'gcr.io/$PROJECT_ID/nodejs:10'
  - 'gcr.io/$PROJECT_ID/nodejs:12'
  - 'gcr.io/$PROJECT_ID/nodejs:14'
  - 'gcr.io/$PROJECT_ID/nodejs:debug'
  - 'gcr.io/$PROJECT_ID/nodejs:10-debug'
  - 'gcr.io/$PROJECT_ID/nodejs:12-debug'
  - 'gcr.io/$PROJECT_ID/nodejs:14-debug'
  - 'gcr.io/$PROJECT_ID/dotnet:latest'
  - 'gcr.io/$PROJECT_ID/dotnet:debug'
  - 'gcr.io/$PROJECT_ID/dotnet-debian9:latest'
  - 'gcr.io/$PROJECT_ID/dotnet-debian9:debug'
  - 'gcr.io/$PROJECT_ID/dotnet-debian10:latest'
  - 'gcr.io/$PROJECT_ID/dotnet-debian10:debug'
  - 'gcr.io/$PROJECT_ID/dotnet/core/aspnet:latest'
  - 'gcr.io/$PROJECT_ID/dotnet/core/aspnet:3.1'
  - 'gcr.io/$PROJECT_ID/dotnet/core/aspnet:debug'
  - 'gcr.io/$PROJECT_ID/dotnet/core/runtime:latest'
  - 'gcr.io/$PROJECT_ID/dotnet/core/runtime:3.1'
  - 'gcr.io/$PROJECT_ID/dotnet/core/runtime:debug'
  - 'gcr.io/$PROJECT_ID/dotnet/core/sdk:latest'
  - 'gcr.io/$PROJECT_ID/dotnet/core/sdk:3.1'
  - 'gcr.io/$PROJECT_ID/dotnet/core/sdk:debug'
