timeout: 1800s
steps:

# Publishing base, cc, and static as latest is handled in a separate release process
- name: gcr.io/cloud-builders/bazel
  entrypoint: sh
  args:
  - -c
  - |
    #!/bin/sh
    set -o errexit
    set -o xtrace
    bazel build --host_force_python=PY2 //package_manager:dpkg_parser.par

    bazel run --host_force_python=PY2 //base:static_debian9
    bazel run --host_force_python=PY2 //base:static_debian10
    bazel run --host_force_python=PY2 //base:static-nonroot_debian9
    bazel run --host_force_python=PY2 //base:static-nonroot_debian10
    bazel run --host_force_python=PY2 //base:base_debian9
    bazel run --host_force_python=PY2 //base:base_debian10
    bazel run --host_force_python=PY2 //base:base-nonroot_debian9
    bazel run --host_force_python=PY2 //base:base-nonroot_debian10
    bazel run --host_force_python=PY2 //base:debug_debian9
    bazel run --host_force_python=PY2 //base:debug_debian10
    bazel run --host_force_python=PY2 //base:debug-nonroot_debian9
    bazel run --host_force_python=PY2 //base:debug-nonroot_debian10

    bazel run --host_force_python=PY2 //cc:cc_debian9
    bazel run --host_force_python=PY2 //cc:cc_debian10
    bazel run --host_force_python=PY2 //cc:debug_debian9
    bazel run --host_force_python=PY2 //cc:debug_debian10
- name: gcr.io/cloud-builders/docker
  entrypoint: sh
  args:
  - -c
  - |
    #!/bin/sh
    set -o errexit
    set -o xtrace
    docker tag bazel/base:static_debian9          gcr.io/$PROJECT_ID/static:${COMMIT_SHA}
    docker tag bazel/base:static_debian9          gcr.io/$PROJECT_ID/static-debian9:${COMMIT_SHA}
    docker tag bazel/base:static_debian10         gcr.io/$PROJECT_ID/static-debian10:${COMMIT_SHA}
    docker tag bazel/base:static-nonroot_debian9  gcr.io/$PROJECT_ID/static:nonroot
    docker tag bazel/base:static-nonroot_debian9  gcr.io/$PROJECT_ID/static-debian9:nonroot
    docker tag bazel/base:static-nonroot_debian10 gcr.io/$PROJECT_ID/static-debian10:nonroot
    docker tag bazel/base:base_debian9            gcr.io/$PROJECT_ID/base:${COMMIT_SHA}
    docker tag bazel/base:base_debian9            gcr.io/$PROJECT_ID/base-debian9:${COMMIT_SHA}
    docker tag bazel/base:base_debian10           gcr.io/$PROJECT_ID/base-debian10:${COMMIT_SHA}
    docker tag bazel/base:base-nonroot_debian9    gcr.io/$PROJECT_ID/base:nonroot
    docker tag bazel/base:base-nonroot_debian9    gcr.io/$PROJECT_ID/base-debian9:nonroot
    docker tag bazel/base:base-nonroot_debian10   gcr.io/$PROJECT_ID/base-debian10:nonroot
    docker tag bazel/base:debug_debian9           gcr.io/$PROJECT_ID/base:debug
    docker tag bazel/base:debug_debian9           gcr.io/$PROJECT_ID/base-debian9:debug
    docker tag bazel/base:debug_debian10          gcr.io/$PROJECT_ID/base-debian10:debug
    docker tag bazel/base:debug-nonroot_debian9   gcr.io/$PROJECT_ID/base:debug-nonroot
    docker tag bazel/base:debug-nonroot_debian9   gcr.io/$PROJECT_ID/base-debian9:debug-nonroot
    docker tag bazel/base:debug-nonroot_debian10  gcr.io/$PROJECT_ID/base-debian10:debug-nonroot

    docker tag bazel/cc:cc_debian9     gcr.io/$PROJECT_ID/cc:${COMMIT_SHA}
    docker tag bazel/cc:cc_debian9     gcr.io/$PROJECT_ID/cc-debian9:${COMMIT_SHA}
    docker tag bazel/cc:cc_debian10    gcr.io/$PROJECT_ID/cc-debian10:${COMMIT_SHA}
    docker tag bazel/cc:debug_debian9  gcr.io/$PROJECT_ID/cc:debug
    docker tag bazel/cc:debug_debian9  gcr.io/$PROJECT_ID/cc-debian9:debug
    docker tag bazel/cc:debug_debian10 gcr.io/$PROJECT_ID/cc-debian10:debug

- name: gcr.io/cloud-builders/bazel
  entrypoint: sh
  args:
  - -c
  - |
    #!/bin/sh
    set -o errexit
    set -o xtrace
    bazel run --host_force_python=PY2 //java:java8_debian9
    bazel run --host_force_python=PY2 //java:java8_debug_debian9
    bazel run --host_force_python=PY2 //java:java11_debian9
    bazel run --host_force_python=PY2 //java:java11_debug_debian9
    bazel run --host_force_python=PY2 //java:java11_debian10
    bazel run --host_force_python=PY2 //java:java11_debug_debian10
    bazel run --host_force_python=PY2 //java/jetty:jetty_java8_debian9
    bazel run --host_force_python=PY2 //java/jetty:jetty_java8_debug_debian9
    bazel run --host_force_python=PY2 //java/jetty:jetty_java11_debian9
    bazel run --host_force_python=PY2 //java/jetty:jetty_java11_debug_debian9
    bazel run --host_force_python=PY2 //java/jetty:jetty_java11_debian10
    bazel run --host_force_python=PY2 //java/jetty:jetty_java11_debug_debian10
- name: gcr.io/cloud-builders/docker
  entrypoint: sh
  args:
  - -c
  - |
    #!/bin/sh
    set -o errexit
    set -o xtrace
    docker tag bazel/java:java8_debian9                     gcr.io/$PROJECT_ID/java:latest
    docker tag bazel/java:java8_debian9                     gcr.io/$PROJECT_ID/java:8
    docker tag bazel/java:java8_debian9                     gcr.io/$PROJECT_ID/java-debian9:latest
    docker tag bazel/java:java8_debian9                     gcr.io/$PROJECT_ID/java-debian9:8
    docker tag bazel/java:java8_debug_debian9               gcr.io/$PROJECT_ID/java:debug
    docker tag bazel/java:java8_debug_debian9               gcr.io/$PROJECT_ID/java:8-debug
    docker tag bazel/java:java8_debug_debian9               gcr.io/$PROJECT_ID/java-debian9:debug
    docker tag bazel/java:java8_debug_debian9               gcr.io/$PROJECT_ID/java-debian9:8-debug
    docker tag bazel/java:java11_debian9                    gcr.io/$PROJECT_ID/java:11
    docker tag bazel/java:java11_debian9                    gcr.io/$PROJECT_ID/java-debian9:11
    docker tag bazel/java:java11_debug_debian9              gcr.io/$PROJECT_ID/java:11-debug
    docker tag bazel/java:java11_debug_debian9              gcr.io/$PROJECT_ID/java-debian9:11-debug
    docker tag bazel/java:java11_debian10                   gcr.io/$PROJECT_ID/java-debian10:latest
    docker tag bazel/java:java11_debian10                   gcr.io/$PROJECT_ID/java-debian10:11
    docker tag bazel/java:java11_debug_debian10             gcr.io/$PROJECT_ID/java-debian10:debug
    docker tag bazel/java:java11_debug_debian10             gcr.io/$PROJECT_ID/java-debian10:11-debug
    docker tag bazel/java/jetty:jetty_java8_debian9         gcr.io/$PROJECT_ID/java/jetty:latest
    docker tag bazel/java/jetty:jetty_java8_debian9         gcr.io/$PROJECT_ID/java/jetty:java8
    docker tag bazel/java/jetty:jetty_java8_debian9         gcr.io/$PROJECT_ID/java-debian9/jetty:latest
    docker tag bazel/java/jetty:jetty_java8_debian9         gcr.io/$PROJECT_ID/java-debian9/jetty:java8
    docker tag bazel/java/jetty:jetty_java8_debug_debian9   gcr.io/$PROJECT_ID/java/jetty:debug
    docker tag bazel/java/jetty:jetty_java8_debug_debian9   gcr.io/$PROJECT_ID/java/jetty:java8-debug
    docker tag bazel/java/jetty:jetty_java8_debug_debian9   gcr.io/$PROJECT_ID/java-debian9/jetty:debug
    docker tag bazel/java/jetty:jetty_java8_debug_debian9   gcr.io/$PROJECT_ID/java-debian9/jetty:java8-debug
    docker tag bazel/java/jetty:jetty_java11_debian9        gcr.io/$PROJECT_ID/java/jetty:java11
    docker tag bazel/java/jetty:jetty_java11_debian9        gcr.io/$PROJECT_ID/java-debian9/jetty:java11
    docker tag bazel/java/jetty:jetty_java11_debug_debian9  gcr.io/$PROJECT_ID/java/jetty:java11-debug
    docker tag bazel/java/jetty:jetty_java11_debug_debian9  gcr.io/$PROJECT_ID/java-debian9/jetty:java11-debug
    docker tag bazel/java/jetty:jetty_java11_debian10       gcr.io/$PROJECT_ID/java-debian10/jetty:latest
    docker tag bazel/java/jetty:jetty_java11_debian10       gcr.io/$PROJECT_ID/java-debian10/jetty:java11
    docker tag bazel/java/jetty:jetty_java11_debug_debian10 gcr.io/$PROJECT_ID/java-debian10/jetty:debug
    docker tag bazel/java/jetty:jetty_java11_debug_debian10 gcr.io/$PROJECT_ID/java-debian10/jetty:java11-debug

- name: gcr.io/cloud-builders/bazel
  entrypoint: sh
  args:
  - -c
  - |
    #!/bin/sh
    set -o errexit
    set -o xtrace
    bazel run --host_force_python=PY2 //experimental/python3:python3_debian9
    bazel run --host_force_python=PY2 //experimental/python3:python3_debian10
    bazel run --host_force_python=PY2 //experimental/python3:debug_debian9
    bazel run --host_force_python=PY2 //experimental/python3:debug_debian10

    bazel run --host_force_python=PY2 //experimental/python2.7:python27_debian9
    bazel run --host_force_python=PY2 //experimental/python2.7:python27_debian10
    bazel run --host_force_python=PY2 //experimental/python2.7:debug_debian9
    bazel run --host_force_python=PY2 //experimental/python2.7:debug_debian10

    bazel run --host_force_python=PY2 //experimental/nodejs
    bazel run --host_force_python=PY2 //experimental/nodejs:debug

    bazel run --host_force_python=PY2 //experimental/dotnet
    bazel run --host_force_python=PY2 //experimental/dotnet:debug
- name: gcr.io/cloud-builders/docker
  entrypoint: sh
  args:
  - -c
  - |
    #!/bin/sh
    set -o errexit
    set -o xtrace
    docker tag bazel/experimental/python3:python3_debian9  gcr.io/$PROJECT_ID/python3:latest
    docker tag bazel/experimental/python3:python3_debian9  gcr.io/$PROJECT_ID/python3-debian9:latest
    docker tag bazel/experimental/python3:python3_debian10 gcr.io/$PROJECT_ID/python3-debian10:latest
    docker tag bazel/experimental/python3:debug_debian9    gcr.io/$PROJECT_ID/python3:debug
    docker tag bazel/experimental/python3:debug_debian9    gcr.io/$PROJECT_ID/python3-debian9:debug
    docker tag bazel/experimental/python3:debug_debian10   gcr.io/$PROJECT_ID/python3-debian10:debug

    docker tag bazel/experimental/python2.7:python27_debian9  gcr.io/$PROJECT_ID/python2.7:latest
    docker tag bazel/experimental/python2.7:python27_debian9  gcr.io/$PROJECT_ID/python2.7-debian9:latest
    docker tag bazel/experimental/python2.7:python27_debian10 gcr.io/$PROJECT_ID/python2.7-debian10:latest
    docker tag bazel/experimental/python2.7:debug_debian9     gcr.io/$PROJECT_ID/python2.7:debug
    docker tag bazel/experimental/python2.7:debug_debian9     gcr.io/$PROJECT_ID/python2.7-debian9:debug
    docker tag bazel/experimental/python2.7:debug_debian10    gcr.io/$PROJECT_ID/python2.7-debian10:debug

    docker tag bazel/experimental/nodejs:nodejs gcr.io/$PROJECT_ID/nodejs:latest
    docker tag bazel/experimental/nodejs:debug  gcr.io/$PROJECT_ID/nodejs:debug

    docker tag bazel/experimental/dotnet:dotnet gcr.io/$PROJECT_ID/dotnet:latest
    docker tag bazel/experimental/dotnet:debug  gcr.io/$PROJECT_ID/dotnet:debug


images:
  - 'gcr.io/$PROJECT_ID/static-debian9:${COMMIT_SHA}'
  - 'gcr.io/$PROJECT_ID/static:${COMMIT_SHA}'
  - 'gcr.io/$PROJECT_ID/static-debian10:${COMMIT_SHA}'
  - 'gcr.io/$PROJECT_ID/static-debian9:nonroot'
  - 'gcr.io/$PROJECT_ID/static:nonroot'
  - 'gcr.io/$PROJECT_ID/static-debian10:nonroot'
  - 'gcr.io/$PROJECT_ID/base-debian9:${COMMIT_SHA}'
  - 'gcr.io/$PROJECT_ID/base:${COMMIT_SHA}'
  - 'gcr.io/$PROJECT_ID/base-debian10:${COMMIT_SHA}'
  - 'gcr.io/$PROJECT_ID/base-debian9:nonroot'
  - 'gcr.io/$PROJECT_ID/base:nonroot'
  - 'gcr.io/$PROJECT_ID/base-debian10:nonroot'
  - 'gcr.io/$PROJECT_ID/base-debian9:debug'
  - 'gcr.io/$PROJECT_ID/base:debug'
  - 'gcr.io/$PROJECT_ID/base-debian10:debug'
  - 'gcr.io/$PROJECT_ID/base-debian9:debug-nonroot'
  - 'gcr.io/$PROJECT_ID/base:debug-nonroot'
  - 'gcr.io/$PROJECT_ID/base-debian10:debug-nonroot'
  - 'gcr.io/$PROJECT_ID/cc-debian9:${COMMIT_SHA}'
  - 'gcr.io/$PROJECT_ID/cc:${COMMIT_SHA}'
  - 'gcr.io/$PROJECT_ID/cc-debian10:${COMMIT_SHA}'
  - 'gcr.io/$PROJECT_ID/cc-debian9:debug'
  - 'gcr.io/$PROJECT_ID/cc:debug'
  - 'gcr.io/$PROJECT_ID/cc-debian10:debug'
  - 'gcr.io/$PROJECT_ID/java:latest'
  - 'gcr.io/$PROJECT_ID/java:8'
  - 'gcr.io/$PROJECT_ID/java:debug'
  - 'gcr.io/$PROJECT_ID/java:8-debug'
  - 'gcr.io/$PROJECT_ID/java:11'
  - 'gcr.io/$PROJECT_ID/java:11-debug'
  - 'gcr.io/$PROJECT_ID/java-debian9:latest'
  - 'gcr.io/$PROJECT_ID/java-debian9:8'
  - 'gcr.io/$PROJECT_ID/java-debian9:debug'
  - 'gcr.io/$PROJECT_ID/java-debian9:8-debug'
  - 'gcr.io/$PROJECT_ID/java-debian9:11'
  - 'gcr.io/$PROJECT_ID/java-debian9:11-debug'
  - 'gcr.io/$PROJECT_ID/java-debian10:latest'
  - 'gcr.io/$PROJECT_ID/java-debian10:11'
  - 'gcr.io/$PROJECT_ID/java-debian10:debug'
  - 'gcr.io/$PROJECT_ID/java-debian10:11-debug'
  - 'gcr.io/$PROJECT_ID/java/jetty:latest'
  - 'gcr.io/$PROJECT_ID/java/jetty:java8'
  - 'gcr.io/$PROJECT_ID/java/jetty:debug'
  - 'gcr.io/$PROJECT_ID/java/jetty:java8-debug'
  - 'gcr.io/$PROJECT_ID/java/jetty:java11'
  - 'gcr.io/$PROJECT_ID/java/jetty:java11-debug'
  - 'gcr.io/$PROJECT_ID/java-debian9/jetty:latest'
  - 'gcr.io/$PROJECT_ID/java-debian9/jetty:java8'
  - 'gcr.io/$PROJECT_ID/java-debian9/jetty:debug'
  - 'gcr.io/$PROJECT_ID/java-debian9/jetty:java8-debug'
  - 'gcr.io/$PROJECT_ID/java-debian9/jetty:java11'
  - 'gcr.io/$PROJECT_ID/java-debian9/jetty:java11-debug'
  - 'gcr.io/$PROJECT_ID/java-debian10/jetty:latest'
  - 'gcr.io/$PROJECT_ID/java-debian10/jetty:java11'
  - 'gcr.io/$PROJECT_ID/java-debian10/jetty:debug'
  - 'gcr.io/$PROJECT_ID/java-debian10/jetty:java11-debug'
  - 'gcr.io/$PROJECT_ID/python3-debian9:latest'
  - 'gcr.io/$PROJECT_ID/python3:latest'
  - 'gcr.io/$PROJECT_ID/python3-debian10:latest'
  - 'gcr.io/$PROJECT_ID/python3-debian9:debug'
  - 'gcr.io/$PROJECT_ID/python3:debug'
  - 'gcr.io/$PROJECT_ID/python3-debian10:debug'
  - 'gcr.io/$PROJECT_ID/python2.7-debian9:latest'
  - 'gcr.io/$PROJECT_ID/python2.7:latest'
  - 'gcr.io/$PROJECT_ID/python2.7-debian10:latest'
  - 'gcr.io/$PROJECT_ID/python2.7-debian9:debug'
  - 'gcr.io/$PROJECT_ID/python2.7:debug'
  - 'gcr.io/$PROJECT_ID/python2.7-debian10:debug'
  - 'gcr.io/$PROJECT_ID/nodejs:latest'
  - 'gcr.io/$PROJECT_ID/nodejs:debug'
  - 'gcr.io/$PROJECT_ID/dotnet:latest'
  - 'gcr.io/$PROJECT_ID/dotnet:debug'
