timeout: 2700s  # 45 minutes

options:
  machineType: N1_HIGHCPU_8

steps:

- name: gcr.io/cloud-marketplace-containers/google/bazel:3.4.1
  env:
  - PROJECT_ID=${PROJECT_ID}
  - COMMIT_SHA=${COMMIT_SHA}
  - REGISTRY=gcr.io
  entrypoint: sh
  args:
  - -c
  - |
    #!/bin/sh
    set -o errexit
    set -o xtrace

    # Make sure python points to python3
    # perhaps the gcr.io/cloud-marketplace-containers/google/bazel image
    # should be doing this though
    update-alternatives --install /usr/bin/python python /usr/bin/python3 0

    bazel build //package_manager:dpkg_parser.par

    # Optional: trigger building package bundles without concurrency to avoid
    # flakiness: https://github.com/GoogleContainerTools/distroless/issues/646
    bazel build --jobs=1 @package_bundle_amd64_debian10//file:packages.bzl
    bazel build --jobs=1 @package_bundle_arm_debian10//file:packages.bzl
    bazel build --jobs=1 @package_bundle_arm64_debian10//file:packages.bzl
    bazel build --jobs=1 @package_bundle_s390x_debian10//file:packages.bzl
    bazel build --jobs=1 @package_bundle_ppc64le_debian10//file:packages.bzl

    bazel build --jobs=1 @package_bundle_amd64_debian11//file:packages.bzl
    bazel build --jobs=1 @package_bundle_arm_debian11//file:packages.bzl
    bazel build --jobs=1 @package_bundle_arm64_debian11//file:packages.bzl
    bazel build --jobs=1 @package_bundle_s390x_debian11//file:packages.bzl
    bazel build --jobs=1 @package_bundle_ppc64le_debian11//file:packages.bzl

    bazel run //:publish
    bazel build all.tar

- name: docker
  env:
  - PROJECT_ID=${PROJECT_ID}
  - COMMIT_SHA=${COMMIT_SHA}
  - REGISTRY=gcr.io
  entrypoint: ./cloudbuild_docker.sh

- name: ubuntu
  entrypoint: ./cloudbuild_jq.sh

- name: gcr.io/projectsigstore/cosign:v1.1.0@sha256:47bdf660ceadb5065aa05af62fd24b184db0fdcb34d5892247035dd0dd2d5c3f
  env:
  - PROJECT_ID=${PROJECT_ID}
  - COMMIT_SHA=${COMMIT_SHA}
  - REGISTRY=gcr.io
  entrypoint: sh
  args:
  - ./cloudbuild_cosign.sh 
