timeout: 2700s  # 45 minutes

steps:

- name: gcr.io/cloud-marketplace-containers/google/bazel:3.4.1
  entrypoint: ./cloudbuild_bazel.sh

- name: docker
  env:
  - PROJECT_ID=${PROJECT_ID}
  - COMMIT_SHA=${COMMIT_SHA}
  entrypoint: ./cloudbuild_docker.sh
