timeout: 1800s
steps:

# Publishing base, cc, and static as latest is handled in a separate release process
- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//base:static_debian9']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/base:static_debian9', 'gcr.io/$PROJECT_ID/static-debian9:${COMMIT_SHA}']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'gcr.io/$PROJECT_ID/static-debian9:${COMMIT_SHA}', 'gcr.io/$PROJECT_ID/static:${COMMIT_SHA}']
- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//base:static_debian10']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/base:static_debian10', 'gcr.io/$PROJECT_ID/static-debian10:${COMMIT_SHA}']

- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//base:static-nonroot_debian9']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/base:static-nonroot_debian9', 'gcr.io/$PROJECT_ID/static-debian9:nonroot']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'gcr.io/$PROJECT_ID/static-debian9:nonroot', 'gcr.io/$PROJECT_ID/static:nonroot']
- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//base:static-nonroot_debian10']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/base:static-nonroot_debian10', 'gcr.io/$PROJECT_ID/static-debian10:nonroot']

- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//base:base_debian9']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/base:base_debian9', 'gcr.io/$PROJECT_ID/base-debian9:${COMMIT_SHA}']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'gcr.io/$PROJECT_ID/base-debian9:${COMMIT_SHA}', 'gcr.io/$PROJECT_ID/base:${COMMIT_SHA}']
- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//base:base_debian10']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/base:base_debian10', 'gcr.io/$PROJECT_ID/base-debian10:${COMMIT_SHA}']

- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//base:base-nonroot_debian9']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/base:base-nonroot_debian9', 'gcr.io/$PROJECT_ID/base-debian9:nonroot']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'gcr.io/$PROJECT_ID/base-debian9:nonroot', 'gcr.io/$PROJECT_ID/base:nonroot']
- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//base:base-nonroot_debian10']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/base:base-nonroot_debian10', 'gcr.io/$PROJECT_ID/base-debian10:nonroot']

- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//base:debug_debian9']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/base:debug_debian9', 'gcr.io/$PROJECT_ID/base-debian9:debug']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'gcr.io/$PROJECT_ID/base-debian9:debug', 'gcr.io/$PROJECT_ID/base:debug']
- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//base:debug_debian10']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/base:debug_debian10', 'gcr.io/$PROJECT_ID/base-debian10:debug']

- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//base:debug-nonroot_debian9']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/base:debug-nonroot_debian9', 'gcr.io/$PROJECT_ID/base-debian9:debug-nonroot']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'gcr.io/$PROJECT_ID/base-debian9:debug-nonroot', 'gcr.io/$PROJECT_ID/base:debug-nonroot']
- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//base:debug-nonroot_debian10']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/base:debug-nonroot_debian10', 'gcr.io/$PROJECT_ID/base-debian10:debug-nonroot']

- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//cc:cc_debian9']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/cc:cc_debian9', 'gcr.io/$PROJECT_ID/cc-debian9:${COMMIT_SHA}']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'gcr.io/$PROJECT_ID/cc-debian9:${COMMIT_SHA}', 'gcr.io/$PROJECT_ID/cc:${COMMIT_SHA}']
- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//cc:cc_debian10']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/cc:cc_debian10', 'gcr.io/$PROJECT_ID/cc-debian10:${COMMIT_SHA}']

- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//cc:debug_debian9']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/cc:debug_debian9', 'gcr.io/$PROJECT_ID/cc-debian9:debug']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'gcr.io/$PROJECT_ID/cc-debian9:debug', 'gcr.io/$PROJECT_ID/cc:debug']
- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//cc:debug_debian10']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/cc:debug_debian10', 'gcr.io/$PROJECT_ID/cc-debian10:debug']

- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//java:java8']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/java:java8', 'gcr.io/$PROJECT_ID/java:latest']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/java:java8', 'gcr.io/$PROJECT_ID/java:8']

- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//java:java8_debug']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/java:java8_debug', 'gcr.io/$PROJECT_ID/java:debug']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/java:java8_debug', 'gcr.io/$PROJECT_ID/java:8-debug']

- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//java:java11']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/java:java11', 'gcr.io/$PROJECT_ID/java:11']

- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//java:java11_debug']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/java:java11_debug', 'gcr.io/$PROJECT_ID/java:11-debug']

- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//java/jetty:jetty_java8']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/java/jetty:jetty_java8', 'gcr.io/$PROJECT_ID/java/jetty:latest']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/java/jetty:jetty_java8', 'gcr.io/$PROJECT_ID/java/jetty:java8']

- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//java/jetty:jetty_java8_debug']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/java/jetty:jetty_java8_debug', 'gcr.io/$PROJECT_ID/java/jetty:debug']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/java/jetty:jetty_java8_debug', 'gcr.io/$PROJECT_ID/java/jetty:java8-debug']

- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//java/jetty:jetty_java11']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/java/jetty:jetty_java11', 'gcr.io/$PROJECT_ID/java/jetty:java11']

- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//java/jetty:jetty_java11_debug']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/java/jetty:jetty_java11_debug', 'gcr.io/$PROJECT_ID/java/jetty:java11-debug']

- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//experimental/python3:python3_debian9']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/experimental/python3:python3_debian9', 'gcr.io/$PROJECT_ID/python3-debian9:latest']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'gcr.io/$PROJECT_ID/python3-debian9:latest', 'gcr.io/$PROJECT_ID/python3:latest']
- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//experimental/python3:python3_debian10']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/experimental/python3:python3_debian10', 'gcr.io/$PROJECT_ID/python3-debian10:latest']

- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//experimental/python3:debug_debian9']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/experimental/python3:debug_debian9', 'gcr.io/$PROJECT_ID/python3-debian9:debug']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'gcr.io/$PROJECT_ID/python3-debian9:debug', 'gcr.io/$PROJECT_ID/python3:debug']
- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//experimental/python3:debug_debian10']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/experimental/python3:debug_debian10', 'gcr.io/$PROJECT_ID/python3-debian10:debug']

- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//experimental/python2.7:python27_debian9']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/experimental/python2.7:python27_debian9', 'gcr.io/$PROJECT_ID/python2.7-debian9:latest']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'gcr.io/$PROJECT_ID/python2.7-debian9:latest', 'gcr.io/$PROJECT_ID/python2.7:latest']
- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//experimental/python2.7:python27_debian10']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/experimental/python2.7:python27_debian10', 'gcr.io/$PROJECT_ID/python2.7-debian10:latest']

- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//experimental/python2.7:debug_debian9']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/experimental/python2.7:debug_debian9', 'gcr.io/$PROJECT_ID/python2.7-debian9:debug']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'gcr.io/$PROJECT_ID/python2.7-debian9:debug', 'gcr.io/$PROJECT_ID/python2.7:debug']
- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//experimental/python2.7:debug_debian10']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/experimental/python2.7:debug_debian10', 'gcr.io/$PROJECT_ID/python2.7-debian10:debug']

- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//experimental/nodejs']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/experimental/nodejs:nodejs', 'gcr.io/$PROJECT_ID/nodejs:latest']

- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//experimental/nodejs:debug']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/experimental/nodejs:debug', 'gcr.io/$PROJECT_ID/nodejs:debug']

- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//experimental/dotnet']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/experimental/dotnet:dotnet', 'gcr.io/$PROJECT_ID/dotnet:latest']

- name: gcr.io/cloud-builders/bazel
  args: ['run', '--host_force_python=PY2', '//experimental/dotnet:debug']
- name: gcr.io/cloud-builders/docker
  args: ['tag', 'bazel/experimental/dotnet:debug', 'gcr.io/$PROJECT_ID/dotnet:debug']


images:
  - 'gcr.io/$PROJECT_ID/static-debian9:${COMMIT_SHA}'
  - 'gcr.io/$PROJECT_ID/static:${COMMIT_SHA}'
  - 'gcr.io/$PROJECT_ID/static-debian10:${COMMIT_SHA}'
  - 'gcr.io/$PROJECT_ID/static-debian9:nonroot'
  - 'gcr.io/$PROJECT_ID/static:nonroot'
  - 'gcr.io/$PROJECT_ID/static-debian10:nonroot'
  - 'gcr.io/$PROJECT_ID/base-debian9:${COMMIT_SHA}'
  - 'gcr.io/$PROJECT_ID/base:${COMMIT_SHA}'
  - 'gcr.io/$PROJECT_ID/base-debian10:${COMMIT_SHA}'
  - 'gcr.io/$PROJECT_ID/base-debian9:nonroot'
  - 'gcr.io/$PROJECT_ID/base:nonroot'
  - 'gcr.io/$PROJECT_ID/base-debian10:nonroot'
  - 'gcr.io/$PROJECT_ID/base-debian9:debug'
  - 'gcr.io/$PROJECT_ID/base:debug'
  - 'gcr.io/$PROJECT_ID/base-debian10:debug'
  - 'gcr.io/$PROJECT_ID/base-debian9:debug-nonroot'
  - 'gcr.io/$PROJECT_ID/base:debug-nonroot'
  - 'gcr.io/$PROJECT_ID/base-debian10:debug-nonroot'
  - 'gcr.io/$PROJECT_ID/cc-debian9:${COMMIT_SHA}'
  - 'gcr.io/$PROJECT_ID/cc:${COMMIT_SHA}'
  - 'gcr.io/$PROJECT_ID/cc-debian10:${COMMIT_SHA}'
  - 'gcr.io/$PROJECT_ID/cc-debian9:debug'
  - 'gcr.io/$PROJECT_ID/cc:debug'
  - 'gcr.io/$PROJECT_ID/cc-debian10:debug'
  - 'gcr.io/$PROJECT_ID/java:latest'
  - 'gcr.io/$PROJECT_ID/java:8'
  - 'gcr.io/$PROJECT_ID/java:debug'
  - 'gcr.io/$PROJECT_ID/java:8-debug'
  - 'gcr.io/$PROJECT_ID/java:11'
  - 'gcr.io/$PROJECT_ID/java:11-debug'
  - 'gcr.io/$PROJECT_ID/java/jetty:latest'
  - 'gcr.io/$PROJECT_ID/java/jetty:java8'
  - 'gcr.io/$PROJECT_ID/java/jetty:debug'
  - 'gcr.io/$PROJECT_ID/java/jetty:java8-debug'
  - 'gcr.io/$PROJECT_ID/java/jetty:java11'
  - 'gcr.io/$PROJECT_ID/java/jetty:java11-debug'
  - 'gcr.io/$PROJECT_ID/python3-debian9:latest'
  - 'gcr.io/$PROJECT_ID/python3:latest'
  - 'gcr.io/$PROJECT_ID/python3-debian10:latest'
  - 'gcr.io/$PROJECT_ID/python3-debian9:debug'
  - 'gcr.io/$PROJECT_ID/python3:debug'
  - 'gcr.io/$PROJECT_ID/python3-debian10:debug'
  - 'gcr.io/$PROJECT_ID/python2.7-debian9:latest'
  - 'gcr.io/$PROJECT_ID/python2.7:latest'
  - 'gcr.io/$PROJECT_ID/python2.7-debian10:latest'
  - 'gcr.io/$PROJECT_ID/python2.7-debian9:debug'
  - 'gcr.io/$PROJECT_ID/python2.7:debug'
  - 'gcr.io/$PROJECT_ID/python2.7-debian10:debug'
  - 'gcr.io/$PROJECT_ID/nodejs:latest'
  - 'gcr.io/$PROJECT_ID/nodejs:debug'
  - 'gcr.io/$PROJECT_ID/dotnet:latest'
  - 'gcr.io/$PROJECT_ID/dotnet:debug'
