timeout: 7200s  # 2 hours

options:
  machineType: N1_HIGHCPU_8

steps:
  # Pick a version from https://console.cloud.google.com/gcr/images/bazel-public/global/bazel
  - name: gcr.io/bazel-public/bazel@sha256:0a9fb6c7bb0db386888a26940e87829ffad4d2a6bc12bcc32523670ef9ea6505
    env:
    - PROJECT_ID=${PROJECT_ID}
    - COMMIT_SHA=${COMMIT_SHA}
    - REGISTRY=gcr.io
    entrypoint: sh
    args:
    - -c
    - |
      #!/bin/sh
      set -o errexit
      set -o xtrace

      # package manager needs wget
      apt-get install wget

      # Make sure python points to python3
      update-alternatives --install /usr/bin/python python /usr/bin/python3 0


      # fetch all dependencies with retries and backoff
      for i in $(seq 5); do bazel fetch --loading_phase_threads=1 //... && break || sleep 20; done

      bazel run //:sign_and_push -- --key $_KMS_VAL
