load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
    
# autogenerated using dotnet-utils
def repositories():

    http_archive(
        name = "dotnet_6-0_sdk_amd64",
        build_file = "//experimental/dotnet:BUILD.dotnet",
        sha256 = "57d146fac54f7c91686a2940d8f098aae91f998cd15b800f29fe88476af66cef",
        type = "tar.gz",
        urls = ["https://download.visualstudio.microsoft.com/download/pr/77d472e5-194c-421e-992d-e4ca1d08e6cc/56c61ac303ddf1b12026151f4f000a2b/dotnet-sdk-6.0.301-linux-x64.tar.gz"],
    )

    http_archive(
        name = "dotnet_6-0_sdk_arm64",
        build_file = "//experimental/dotnet:BUILD.dotnet",
        sha256 = "562462991b120ce07c114668566db1d8a222b1c9821608dc30df2bfd4ed2d0e5",
        type = "tar.gz",
        urls = ["https://download.visualstudio.microsoft.com/download/pr/06c4ee8e-bf2c-4e46-ab1c-e14dd72311c1/f7bc6c9677eaccadd1d0e76c55d361ea/dotnet-sdk-6.0.301-linux-arm64.tar.gz"],
    )

    http_archive(
        name = "dotnet_6-0_aspnetcore_amd64",
        build_file = "//experimental/dotnet:BUILD.dotnet",
        sha256 = "38ad01d083f0f493116bd06dd80210589abc8b3d502cf81c5dc40ba0fc19d3d5",
        type = "tar.gz",
        urls = ["https://download.visualstudio.microsoft.com/download/pr/afd5344f-a9e9-45f9-85b5-de4551c53736/c30996daa407f9bb540ebc5edfcf16fc/aspnetcore-runtime-6.0.6-linux-x64.tar.gz"],
    )

    http_archive(
        name = "dotnet_6-0_aspnetcore_arm64",
        build_file = "//experimental/dotnet:BUILD.dotnet",
        sha256 = "e80fbf9feed47e2214c848ac66bdf10ce19ddcd5a06a05ec9b255a7915bd43fd",
        type = "tar.gz",
        urls = ["https://download.visualstudio.microsoft.com/download/pr/94553ccb-ce1a-401c-8840-bdffb4e9d0cb/ab8a0024df90506d953904ac38b5a978/aspnetcore-runtime-6.0.6-linux-arm64.tar.gz"],
    )

    http_archive(
        name = "dotnet_6-0_runtime_amd64",
        build_file = "//experimental/dotnet:BUILD.dotnet",
        sha256 = "9a3e9b9f39ca51c354725738fea4b931dd4a85e30d0373f0dd2c0517f7de65ac",
        type = "tar.gz",
        urls = ["https://download.visualstudio.microsoft.com/download/pr/ec4172e3-077a-42c0-859d-349e517d7935/82d945cdc4c33fbe440a86a240a58a41/dotnet-runtime-6.0.6-linux-x64.tar.gz"],
    )

    http_archive(
        name = "dotnet_6-0_runtime_arm64",
        build_file = "//experimental/dotnet:BUILD.dotnet",
        sha256 = "d93230446632671f579e2b1aaa7b82b4c0b53c5e66fbdecfc7e9c78c2ac27fe3",
        type = "tar.gz",
        urls = ["https://download.visualstudio.microsoft.com/download/pr/44ed3398-9838-4fd0-b225-60d5aadfb00e/00fd4a320d09a380753b45106e2a8e94/dotnet-runtime-6.0.6-linux-arm64.tar.gz"],
    )
