load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
    
# autogenerated using dotnet-utils
def repositories():

    http_archive(
        name = "dotnet_6-0_sdk_amd64",
        build_file = "//experimental/dotnet:BUILD.dotnet",
        sha256 = "883a25a15a6aa9d74ae35b23efdb6dced85e52b9519fc590313cec6c2626af79",
        type = "tar.gz",
        urls = ["https://download.visualstudio.microsoft.com/download/pr/0e83f50a-0619-45e6-8f16-dc4f41d1bb16/e0de908b2f070ef9e7e3b6ddea9d268c/dotnet-sdk-6.0.302-linux-x64.tar.gz"],
    )

    http_archive(
        name = "dotnet_6-0_sdk_arm64",
        build_file = "//experimental/dotnet:BUILD.dotnet",
        sha256 = "eefcb70438113652d2f732bb21dfc1e9b9d442151a2d8881c94fd04905333645",
        type = "tar.gz",
        urls = ["https://download.visualstudio.microsoft.com/download/pr/33389348-a7d7-41ae-850f-ec46d3ca9612/36bad11f948b05a4fa9faac93c35e574/dotnet-sdk-6.0.302-linux-arm64.tar.gz"],
    )

    http_archive(
        name = "dotnet_6-0_aspnetcore_amd64",
        build_file = "//experimental/dotnet:BUILD.dotnet",
        sha256 = "61c2b79cc31e1d5df9a398766044177cecb7b9c2baad4ef9d011723ba21fd0ee",
        type = "tar.gz",
        urls = ["https://download.visualstudio.microsoft.com/download/pr/98271725-1784-407c-841a-64d87c674512/b433af33506c816e3b5838f5c65d990a/aspnetcore-runtime-6.0.7-linux-x64.tar.gz"],
    )

    http_archive(
        name = "dotnet_6-0_aspnetcore_arm64",
        build_file = "//experimental/dotnet:BUILD.dotnet",
        sha256 = "b0f7908e4eb7819ff08fc3a4670c52a73035bbea11bebf7d2ef0c39e829cfdc8",
        type = "tar.gz",
        urls = ["https://download.visualstudio.microsoft.com/download/pr/b79c5fa9-a08d-4534-9424-4bacfc3cdc3d/449179d6fe8cda05f52b7be0f6828eb0/aspnetcore-runtime-6.0.7-linux-arm64.tar.gz"],
    )

    http_archive(
        name = "dotnet_6-0_runtime_amd64",
        build_file = "//experimental/dotnet:BUILD.dotnet",
        sha256 = "6ed407c5c6d365673e707bd9532a0db78d43fbdb2cea99674a841c784cba5063",
        type = "tar.gz",
        urls = ["https://download.visualstudio.microsoft.com/download/pr/bd828687-1706-4041-a804-5e93631fe256/d4ec75936459a7e8c772c929edcbfeda/dotnet-runtime-6.0.7-linux-x64.tar.gz"],
    )

    http_archive(
        name = "dotnet_6-0_runtime_arm64",
        build_file = "//experimental/dotnet:BUILD.dotnet",
        sha256 = "149b6ef26606fec97262ff1e8c45f17fc8dbc67e5ea2f5e2cd0f6d55aa48c8eb",
        type = "tar.gz",
        urls = ["https://download.visualstudio.microsoft.com/download/pr/f9706e92-c7a1-4dc8-806a-0e95827c5b02/23be52946e4e2425c798208c5f16bb64/dotnet-runtime-6.0.7-linux-arm64.tar.gz"],
    )
