apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-distroless
  annotations:
    chains.tekton.dev/transparency-upload: "true"
    description: |
      Takes in the distroless repo as an input and builds & pushes distroless images.
spec:
  params:
    - name: PROJECT_ID
      type: string
      default: distroless
    - name: CHAINS-GIT_COMMIT
      type: string
    - name: CHAINS-GIT_URL
      type: string
      default: https://github.com/GoogleContainerTools/distroless
  workspaces:
  - name: source
    mountPath: /go/src/github.com/GoogleContainerTools/distroless
  steps:
    # Unfortunately gcr.io/cloud-marketplace-containers/google/bazel is
    # no longer maintained. The cloud-build project is, but does not tag
    # images with bazel versions. The SHA hash was found manually and
    # verified with:
    #
    #   docker pull gcr.io/cloud-builders/bazel
    #   docker run --rm -ti gcr.io/cloud-builders/bazel version
    #   docker image inspect gcr.io/cloud-builders/bazel --format '{{.Id}}'
    #
    # See: https://github.com/GoogleCloudPlatform/cloud-builders/issues/667
    - name: bazel
      image: gcr.io/cloud-builders/bazel@sha256:a7ab9f3abba94aad648d5fa9f690d285c0f55d8b20a411a3d53ca22a2ab9ad50
      workingDir: $(workspaces.source.path)
      env:
      - name: PROJECT_ID
        value: $(params.PROJECT_ID)
      - name: REGISTRY
        value: insecure-registry.default.svc.cluster.local:5000
      - name: COMMIT_SHA
        value: $(params.CHAINS-GIT_COMMIT)
      timeout: 2h
      script: |
        #!/bin/sh
        set -ex

        # package manager needs wget
        apt-get install wget

        # Make sure python points to python3
        update-alternatives --install /usr/bin/python python /usr/bin/python3 0

        bazel build all.tar
        
        # install jq and create the images file
        ./cloudbuild_jq.sh

        bazel run //:publish
