apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: chains
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    pipeline.tekton.dev/release: devel
    version: devel
  name: chains-config
  namespace: tekton-chains
data:
  artifacts.oci.signer: kms
  artifacts.oci.storage: oci
  artifacts.taskrun.format: in-toto
  artifacts.taskrun.signer: kms
  artifacts.taskrun.storage: oci
  signers.kms.kmsref: gcpkms://projects/distroless/locations/global/keyRings/cosign/cryptoKeys/cosign
  storage.oci.repository.insecure: "true"
  transparency.enabled: "true"
