apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: distroless-provenance
  annotations:
    chains.tekton.dev/transparency-upload: "true"
    description: |
      Takes in the distroless repo as an input and builds & pushes distroless images.
spec:
  results:
    - name: IMAGES
  params:
    - name: MANIFEST_SUBSECTION
      type: string
    - name: CHAINS-GIT_COMMIT
      type: string
    - name: CHAINS-GIT_URL
      type: string
  workspaces:
  - name: source
    mountPath: /go/src/github.com/GoogleContainerTools/distroless
  steps:
    - name: provenance
      image: golang:1.16
      workingDir: $(workspaces.source.path)
      env:
      - name: REGISTRY
        value: insecure-registry.default.svc.cluster.local:5000
      script: |
        #!/bin/sh
        set -ex

        # get the digests for a subset of images built, and store in the IMAGES result
        (cd provenance; go build -o provenance provenance.go)
        ./provenance/provenance images $(params.MANIFEST_SUBSECTION) > $(results.IMAGES.path)
