"node"

BUILD_TMPL = """\
# GENERATED BY node_archive.bzl
load("@distroless//private/pkg:debian_spdx.bzl", "debian_spdx")
load("@distroless//private/util:merge_providers.bzl", "merge_providers")
load("@distroless//private/util:tar.bzl", "tar")

tar(
    name = "data",
    extension = "tar.gz",
    srcs = glob(
        [
            "output/bin/node",
            "output/LICENSE",
        ],
    ),
    package_dir = "/nodejs",
    strip_prefix = "external/{canonical_name}/output"
)

tar(
    name = "_control",
    extension = "tar.gz",
    srcs = ["control"]
)

debian_spdx(
    name = "spdx",
    control = ":_control",
    data = ":data",
    package_name = "{package_name}",
    spdx_id = "{spdx_id}",
    sha256 = "{sha256}",
    urls = [{urls}]
)

merge_providers(
    name = "{name}",
    srcs = [":data", ":spdx"],
    visibility = ["//visibility:public"],
)
"""

def _impl(rctx):
    rctx.report_progress("Fetching {}".format(rctx.attr.package_name))
    rctx.download_and_extract(
        url = rctx.attr.urls,
        sha256 = rctx.attr.sha256,
        type = rctx.attr.type,
        stripPrefix = rctx.attr.strip_prefix,
        output = "output",
    )
    rctx.template(
        "control",
        rctx.attr.control,
        substitutions = {
            "{{VERSION}}": rctx.attr.version,
            "{{ARCHITECTURE}}": rctx.attr.architecture,
            "{{SHA256}}": rctx.attr.sha256,
        },
    )
    rctx.file(
        "BUILD.bazel",
        content = BUILD_TMPL.format(
            canonical_name = rctx.attr.name,
            name = rctx.attr.name.split("~")[-1],
            package_name = rctx.attr.package_name,
            spdx_id = rctx.attr.name,
            urls = ",".join(['"%s"' % url for url in rctx.attr.urls]),
            sha256 = rctx.attr.sha256,
        ),
    )

node_archive = repository_rule(
    implementation = _impl,
    attrs = {
        "urls": attr.string_list(mandatory = True),
        "sha256": attr.string(mandatory = True),
        "type": attr.string(default = ".tar.gz"),
        "strip_prefix": attr.string(),
        "package_name": attr.string(default = "nodejs"),
        "version": attr.string(mandatory = True),
        "architecture": attr.string(mandatory = True),
        # control is only used to populate the sbom, see https://github.com/GoogleContainerTools/distroless/issues/1373
        # for why writing debian control files to the image is incompatible with scanners.
        "control": attr.label(),
    },
)

def _node_impl(module_ctx):
    mod = module_ctx.modules[0]

    if len(module_ctx.modules) > 1:
        fail("node.archive should be called only once")
    if not mod.is_root:
        fail("node.archive should be called from root module only.")

    # Node (https://nodejs.org/en/about/releases/)
    # Follow Node's maintenance schedule and support all LTS versions that are not end of life

    node_archive(
        name = "nodejs22_amd64",
        sha256 = "c7a10d6816da8eaaa7534dd73c71c6e2b2c391dbbf845e364902d156615dd1b8",
        strip_prefix = "node-v22.22.3-linux-x64/",
        urls = ["https://nodejs.org/dist/v22.22.3/node-v22.22.3-linux-x64.tar.gz"],
        version = "22.22.3",
        architecture = "amd64",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs22_arm64",
        sha256 = "cc8bc82b2dd0b595c3b95a4c3c9c8c350907cff011afbdee3d1379e812e1e3e3",
        strip_prefix = "node-v22.22.3-linux-arm64/",
        urls = ["https://nodejs.org/dist/v22.22.3/node-v22.22.3-linux-arm64.tar.gz"],
        version = "22.22.3",
        architecture = "arm64",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs22_arm",
        sha256 = "18fbe1bfdd42045af15f02256ae3e59490d1b9ff93dfc27a223acc2c92740250",
        strip_prefix = "node-v22.22.3-linux-armv7l/",
        urls = ["https://nodejs.org/dist/v22.22.3/node-v22.22.3-linux-armv7l.tar.gz"],
        version = "22.22.3",
        architecture = "arm",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs22_ppc64le",
        sha256 = "a90f523cf164e1c761bf4c59b5c6aa0d9d552892701ab69499e683ee1fc06bbc",
        strip_prefix = "node-v22.22.3-linux-ppc64le/",
        urls = ["https://nodejs.org/dist/v22.22.3/node-v22.22.3-linux-ppc64le.tar.gz"],
        version = "22.22.3",
        architecture = "ppc64le",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs22_s390x",
        sha256 = "4b84e43c29d90e4f901815c399106a49af4ee730d12933af82c82d4dc450308c",
        strip_prefix = "node-v22.22.3-linux-s390x/",
        urls = ["https://nodejs.org/dist/v22.22.3/node-v22.22.3-linux-s390x.tar.gz"],
        version = "22.22.3",
        architecture = "s390x",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs24_amd64",
        sha256 = "44836872d9aec49f1e6b52a9a922872db9a2b02d235a616a5681b6a85fec8d89",
        strip_prefix = "node-v24.15.0-linux-x64/",
        urls = ["https://nodejs.org/dist/v24.15.0/node-v24.15.0-linux-x64.tar.gz"],
        version = "24.15.0",
        architecture = "amd64",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs24_arm64",
        sha256 = "73afc234d558c24919875f51c2d1ea002a2ada4ea6f83601a383869fefa64eed",
        strip_prefix = "node-v24.15.0-linux-arm64/",
        urls = ["https://nodejs.org/dist/v24.15.0/node-v24.15.0-linux-arm64.tar.gz"],
        version = "24.15.0",
        architecture = "arm64",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs24_ppc64le",
        sha256 = "b1f88900a4b16365eaba56269304fc11da7581dbf03552d4495f9ace1fc05f6d",
        strip_prefix = "node-v24.15.0-linux-ppc64le/",
        urls = ["https://nodejs.org/dist/v24.15.0/node-v24.15.0-linux-ppc64le.tar.gz"],
        version = "24.15.0",
        architecture = "ppc64le",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs24_s390x",
        sha256 = "f985455439d52fe9b8de6a8f6d07bfeccc736dea527e87eacafe5a8d7516a380",
        strip_prefix = "node-v24.15.0-linux-s390x/",
        urls = ["https://nodejs.org/dist/v24.15.0/node-v24.15.0-linux-s390x.tar.gz"],
        version = "24.15.0",
        architecture = "s390x",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs26_amd64",
        sha256 = "62d555c329e05e3625109f2e3a8b5195b368d5ef38266292469d32f63cd98ffd",
        strip_prefix = "node-v26.1.0-linux-x64/",
        urls = ["https://nodejs.org/dist/v26.1.0/node-v26.1.0-linux-x64.tar.gz"],
        version = "26.1.0",
        architecture = "amd64",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs26_arm64",
        sha256 = "fcb4c339eef70c909cae72091008a6497278e2d0fcd221c0653068cf4ea4f0c7",
        strip_prefix = "node-v26.1.0-linux-arm64/",
        urls = ["https://nodejs.org/dist/v26.1.0/node-v26.1.0-linux-arm64.tar.gz"],
        version = "26.1.0",
        architecture = "arm64",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs26_ppc64le",
        sha256 = "f3ee72a29d3d25a626bae1672667a500b12c284fcfc00f5d6162e3762ebf173f",
        strip_prefix = "node-v26.1.0-linux-ppc64le/",
        urls = ["https://nodejs.org/dist/v26.1.0/node-v26.1.0-linux-ppc64le.tar.gz"],
        version = "26.1.0",
        architecture = "ppc64le",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs26_s390x",
        sha256 = "6e381e4a3b353f335d297abfe4c7d9485459247519df10445b17cc89d8c7f7a5",
        strip_prefix = "node-v26.1.0-linux-s390x/",
        urls = ["https://nodejs.org/dist/v26.1.0/node-v26.1.0-linux-s390x.tar.gz"],
        version = "26.1.0",
        architecture = "s390x",
        control = "//nodejs:control",
    )

    return module_ctx.extension_metadata(
        root_module_direct_deps = [
            "nodejs22_amd64",
            "nodejs22_arm64",
            "nodejs22_arm",
            "nodejs22_ppc64le",
            "nodejs22_s390x",
            "nodejs24_amd64",
            "nodejs24_arm64",
            "nodejs24_ppc64le",
            "nodejs24_s390x",
            "nodejs26_amd64",
            "nodejs26_arm64",
            "nodejs26_ppc64le",
            "nodejs26_s390x",
        ],
        root_module_direct_dev_deps = [],
    )

_archive = tag_class(attrs = {})

node = module_extension(
    implementation = _node_impl,
    tag_classes = {
        "archive": _archive,
    },
)
