"node"

BUILD_TMPL = """\
# GENERATED BY node_archive.bzl
load("@distroless//private/pkg:debian_spdx.bzl", "debian_spdx")
load("@distroless//private/util:merge_providers.bzl", "merge_providers")
load("@distroless//private/util:tar.bzl", "tar")

tar(
    name = "data",
    extension = "tar.gz",
    srcs = glob(
        [
            "output/bin/node",
            "output/LICENSE",
        ],
    ),
    package_dir = "/nodejs",
    strip_prefix = "external/{canonical_name}/output"
)

tar(
    name = "_control",
    extension = "tar.gz",
    srcs = ["control"]
)

debian_spdx(
    name = "spdx",
    control = ":_control",
    data = ":data",
    package_name = "{package_name}",
    spdx_id = "{spdx_id}",
    sha256 = "{sha256}",
    urls = [{urls}]
)

merge_providers(
    name = "{name}",
    srcs = [":data", ":spdx"],
    visibility = ["//visibility:public"],
)
"""

def _impl(rctx):
    rctx.report_progress("Fetching {}".format(rctx.attr.package_name))
    rctx.download_and_extract(
        url = rctx.attr.urls,
        sha256 = rctx.attr.sha256,
        type = rctx.attr.type,
        stripPrefix = rctx.attr.strip_prefix,
        output = "output",
    )
    rctx.template(
        "control",
        rctx.attr.control,
        substitutions = {
            "{{VERSION}}": rctx.attr.version,
            "{{ARCHITECTURE}}": rctx.attr.architecture,
            "{{SHA256}}": rctx.attr.sha256,
        },
    )
    rctx.file(
        "BUILD.bazel",
        content = BUILD_TMPL.format(
            canonical_name = rctx.attr.name,
            name = rctx.attr.name.split("~")[-1],
            package_name = rctx.attr.package_name,
            spdx_id = rctx.attr.name,
            urls = ",".join(['"%s"' % url for url in rctx.attr.urls]),
            sha256 = rctx.attr.sha256,
        ),
    )

node_archive = repository_rule(
    implementation = _impl,
    attrs = {
        "urls": attr.string_list(mandatory = True),
        "sha256": attr.string(mandatory = True),
        "type": attr.string(default = ".tar.gz"),
        "strip_prefix": attr.string(),
        "package_name": attr.string(default = "nodejs"),
        "version": attr.string(mandatory = True),
        "architecture": attr.string(mandatory = True),
        # control is only used to populate the sbom, see https://github.com/GoogleContainerTools/distroless/issues/1373
        # for why writing debian control files to the image is incompatible with scanners.
        "control": attr.label(),
    },
)

def _node_impl(module_ctx):
    mod = module_ctx.modules[0]

    if len(module_ctx.modules) > 1:
        fail("node.archive should be called only once")
    if not mod.is_root:
        fail("node.archive should be called from root module only.")

    # Node (https://nodejs.org/en/about/releases/)
    # Follow Node's maintenance schedule and support all LTS versions that are not end of life

    node_archive(
        name = "nodejs22_amd64",
        sha256 = "7a8cb04b4a1df4eaf432125324b81b29a088e73570a23259a8de1c65d07fc129",
        strip_prefix = "node-v22.23.1-linux-x64/",
        urls = ["https://nodejs.org/dist/v22.23.1/node-v22.23.1-linux-x64.tar.gz"],
        version = "22.23.1",
        architecture = "amd64",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs22_arm64",
        sha256 = "543fa39e57d4c07855939459a323f4deb9a79dd1bb45e6e99458b0f2de10db8d",
        strip_prefix = "node-v22.23.1-linux-arm64/",
        urls = ["https://nodejs.org/dist/v22.23.1/node-v22.23.1-linux-arm64.tar.gz"],
        version = "22.23.1",
        architecture = "arm64",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs22_arm",
        sha256 = "03c56ac0bd3ef3cce967c2f7b2f7ac2259a4ae7ceeaa661291aadf65729a8b53",
        strip_prefix = "node-v22.23.1-linux-armv7l/",
        urls = ["https://nodejs.org/dist/v22.23.1/node-v22.23.1-linux-armv7l.tar.gz"],
        version = "22.23.1",
        architecture = "arm",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs22_ppc64le",
        sha256 = "75ba0ad4949cc90fe0cf5f1e0c28bb7e5d17c1edaecd35dbf01f5830f9b3b552",
        strip_prefix = "node-v22.23.1-linux-ppc64le/",
        urls = ["https://nodejs.org/dist/v22.23.1/node-v22.23.1-linux-ppc64le.tar.gz"],
        version = "22.23.1",
        architecture = "ppc64le",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs22_s390x",
        sha256 = "94c7c55553ad5520172f5bfbd143389eebd1e6a200a5e2d8d309e9ed73f370e5",
        strip_prefix = "node-v22.23.1-linux-s390x/",
        urls = ["https://nodejs.org/dist/v22.23.1/node-v22.23.1-linux-s390x.tar.gz"],
        version = "22.23.1",
        architecture = "s390x",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs24_amd64",
        sha256 = "783130984963db7ba9cbd01089eaf2c2efb055c7c1693c943174b967b3050cb8",
        strip_prefix = "node-v24.18.0-linux-x64/",
        urls = ["https://nodejs.org/dist/v24.18.0/node-v24.18.0-linux-x64.tar.gz"],
        version = "24.18.0",
        architecture = "amd64",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs24_arm64",
        sha256 = "6b4484c2190274175df9aa8f28e2d758a819cb1c1fe6ab481e2f95b463ab8508",
        strip_prefix = "node-v24.18.0-linux-arm64/",
        urls = ["https://nodejs.org/dist/v24.18.0/node-v24.18.0-linux-arm64.tar.gz"],
        version = "24.18.0",
        architecture = "arm64",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs24_ppc64le",
        sha256 = "fe1338972f79283c6bc21e61dbf4576bbe8c05aded2999d41c8643ad30265142",
        strip_prefix = "node-v24.18.0-linux-ppc64le/",
        urls = ["https://nodejs.org/dist/v24.18.0/node-v24.18.0-linux-ppc64le.tar.gz"],
        version = "24.18.0",
        architecture = "ppc64le",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs24_s390x",
        sha256 = "371ebc13945fc169493e752f2ddafafab6ecd8ccb451bcff46e09f69c5dd8c7a",
        strip_prefix = "node-v24.18.0-linux-s390x/",
        urls = ["https://nodejs.org/dist/v24.18.0/node-v24.18.0-linux-s390x.tar.gz"],
        version = "24.18.0",
        architecture = "s390x",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs26_amd64",
        sha256 = "f221dab30d0e9d544332f06fbee2c62186c97d864d5cac8482dba34f1e38b8dc",
        strip_prefix = "node-v26.4.0-linux-x64/",
        urls = ["https://nodejs.org/dist/v26.4.0/node-v26.4.0-linux-x64.tar.gz"],
        version = "26.4.0",
        architecture = "amd64",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs26_arm64",
        sha256 = "773d9ec67266838270ddc105c2548ae8aaff28bc8fe6f34c55d1094043c4165e",
        strip_prefix = "node-v26.4.0-linux-arm64/",
        urls = ["https://nodejs.org/dist/v26.4.0/node-v26.4.0-linux-arm64.tar.gz"],
        version = "26.4.0",
        architecture = "arm64",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs26_ppc64le",
        sha256 = "d550366058fb29aade118fe0552f2fadc694da9ea63aadf4a73d6a523398e139",
        strip_prefix = "node-v26.4.0-linux-ppc64le/",
        urls = ["https://nodejs.org/dist/v26.4.0/node-v26.4.0-linux-ppc64le.tar.gz"],
        version = "26.4.0",
        architecture = "ppc64le",
        control = "//nodejs:control",
    )

    node_archive(
        name = "nodejs26_s390x",
        sha256 = "70ebd033c50f9083be53d8a0583c215049c63212087835da719c3c06cce4117b",
        strip_prefix = "node-v26.4.0-linux-s390x/",
        urls = ["https://nodejs.org/dist/v26.4.0/node-v26.4.0-linux-s390x.tar.gz"],
        version = "26.4.0",
        architecture = "s390x",
        control = "//nodejs:control",
    )

    return module_ctx.extension_metadata(
        root_module_direct_deps = [
            "nodejs22_amd64",
            "nodejs22_arm64",
            "nodejs22_arm",
            "nodejs22_ppc64le",
            "nodejs22_s390x",
            "nodejs24_amd64",
            "nodejs24_arm64",
            "nodejs24_ppc64le",
            "nodejs24_s390x",
            "nodejs26_amd64",
            "nodejs26_arm64",
            "nodejs26_ppc64le",
            "nodejs26_s390x",
        ],
        root_module_direct_dev_deps = [],
    )

_archive = tag_class(attrs = {})

node = module_extension(
    implementation = _node_impl,
    tag_classes = {
        "archive": _archive,
    },
)
