"python"

BUILD_TMPL = """\
# GENERATED BY python_archive.bzl
load("@distroless//private/pkg:debian_spdx.bzl", "debian_spdx")
load("@distroless//private/util:merge_providers.bzl", "merge_providers")
load("@distroless//private/util:tar.bzl", "tar")

tar(
    name = "data",
    extension = "tar.gz",
    srcs = glob(
        [
            "output/bin/python{pyver}",
            "output/lib/python{pyver}/**",
            "output/lib/libpython{pyver}*",
        ],
        exclude = [
            "output/lib/python{pyver}/site-packages/pip/**",
            "output/lib/python{pyver}/site-packages/pip-*.dist-info/**",
        ],
    ),
    symlinks = {{
        "/python/bin/python": "python{pyver}",
        "/python/bin/python3": "python{pyver}",
    }},
    package_dir = "/python",
    strip_prefix = "external/{canonical_name}/output"
)

tar(
    name = "_control",
    extension = "tar.gz",
    srcs = ["control"]
)

debian_spdx(
    name = "spdx",
    control = ":_control",
    data = ":data",
    package_name = "{package_name}",
    spdx_id = "{spdx_id}",
    sha256 = "{sha256}",
    urls = [{urls}]
)

merge_providers(
    name = "{name}",
    srcs = [":data", ":spdx"],
    visibility = ["//visibility:public"],
)
"""

def _impl(rctx):
    rctx.report_progress("Fetching {}".format(rctx.attr.package_name))
    rctx.download_and_extract(
        url = rctx.attr.urls,
        sha256 = rctx.attr.sha256,
        type = rctx.attr.type,
        stripPrefix = rctx.attr.strip_prefix,
        output = "output",
    )
    rctx.template(
        "control",
        rctx.attr.control,
        substitutions = {
            "{{VERSION}}": rctx.attr.version,
            "{{ARCHITECTURE}}": rctx.attr.architecture,
            "{{SHA256}}": rctx.attr.sha256,
        },
    )
    rctx.file(
        "BUILD.bazel",
        content = BUILD_TMPL.format(
            canonical_name = rctx.attr.name,
            name = rctx.attr.name.split("~")[-1],
            package_name = rctx.attr.package_name,
            spdx_id = rctx.attr.name,
            pyver = rctx.attr.python_version,
            urls = ",".join(['"%s"' % url for url in rctx.attr.urls]),
            sha256 = rctx.attr.sha256,
        ),
    )

python_archive = repository_rule(
    implementation = _impl,
    attrs = {
        "urls": attr.string_list(mandatory = True),
        "sha256": attr.string(mandatory = True),
        "type": attr.string(default = ".tar.gz"),
        "strip_prefix": attr.string(),
        "package_name": attr.string(default = "python"),
        "version": attr.string(mandatory = True),
        # the x.y version used for bin/lib paths, e.g. "3.14"
        "python_version": attr.string(mandatory = True),
        "architecture": attr.string(mandatory = True),
        # control is only used to populate the sbom, see https://github.com/GoogleContainerTools/distroless/issues/1373
        # for why writing debian control files to the image is incompatible with scanners.
        "control": attr.label(),
    },
)

_PYTHON_VERSIONS_TMPL = """\
"python versions"

# AUTO GENERATED. DO NOT EDIT.
PYTHON_VERSIONS = {versions}
"""

def _python_versions_repo_impl(rctx):
    rctx.file("versions.bzl", _PYTHON_VERSIONS_TMPL.format(versions = str(rctx.attr.versions)))
    rctx.file("BUILD.bazel", 'exports_files(["versions.bzl"])')

python_versions_repo = repository_rule(
    implementation = _python_versions_repo_impl,
    attrs = {
        "versions": attr.string_dict(),
    },
)

def _python_impl(module_ctx):
    mod = module_ctx.modules[0]

    if len(module_ctx.modules) > 1:
        fail("python.archive should be called only once")
    if not mod.is_root:
        fail("python.archive should be called from root module only.")

    # Python from python-build-standalone (https://github.com/astral-sh/python-build-standalone)
    # Release 20260814. Linux targets only (distroless images).
    # Versions 3.13, 3.14 (new minors added by update-python-archives when stable).
    # NOTE: armv7 is intentionally absent: PBS publishes soft-float gnueabi builds
    # (interpreter /lib/ld-linux.so.3) which cannot run on the distroless armhf base
    # (loader /usr/lib/ld-linux-armhf.so.3); ppc64le is not published by PBS.
    python_archive(
        name = "python313_amd64",
        sha256 = "45816a2653b47a6cc48d8ada4ea1185758a4c2db389d012b31e0205e5ccb548b",
        strip_prefix = "python/",
        urls = ["https://github.com/astral-sh/python-build-standalone/releases/download/20260814/cpython-3.13.15+20260814-x86_64-unknown-linux-gnu-install_only.tar.gz"],
        version = "3.13.15+20260814",
        python_version = "3.13",
        architecture = "amd64",
        control = "//python:control",
    )

    python_archive(
        name = "python313_arm64",
        sha256 = "303efcce34b86fd8b0d8a260327dbf8d0d4fba6d2d77b2bca311e8bbd19265e1",
        strip_prefix = "python/",
        urls = ["https://github.com/astral-sh/python-build-standalone/releases/download/20260814/cpython-3.13.15+20260814-aarch64-unknown-linux-gnu-install_only.tar.gz"],
        version = "3.13.15+20260814",
        python_version = "3.13",
        architecture = "arm64",
        control = "//python:control",
    )

    python_archive(
        name = "python313_s390x",
        sha256 = "41b878867844e56a2757bef4dfdb906596ffc43c0a9a816e5b3f38dc09c97d8e",
        strip_prefix = "python/",
        urls = ["https://github.com/astral-sh/python-build-standalone/releases/download/20260814/cpython-3.13.15+20260814-s390x-unknown-linux-gnu-install_only.tar.gz"],
        version = "3.13.15+20260814",
        python_version = "3.13",
        architecture = "s390x",
        control = "//python:control",
    )

    python_archive(
        name = "python313_riscv64",
        sha256 = "f6c666d439a46d6729e211e465362233d2b3f94d4cc9cf117b1d1045fca62b9c",
        strip_prefix = "python/",
        urls = ["https://github.com/astral-sh/python-build-standalone/releases/download/20260814/cpython-3.13.15+20260814-riscv64-unknown-linux-gnu-install_only.tar.gz"],
        version = "3.13.15+20260814",
        python_version = "3.13",
        architecture = "riscv64",
        control = "//python:control",
    )

    python_archive(
        name = "python314_amd64",
        sha256 = "490953e4a7e97a6ed64d0f0bd04f2d4d9a7bb45368890d3fa32ba05d0ff5c48f",
        strip_prefix = "python/",
        urls = ["https://github.com/astral-sh/python-build-standalone/releases/download/20260814/cpython-3.14.7+20260814-x86_64-unknown-linux-gnu-install_only.tar.gz"],
        version = "3.14.7+20260814",
        python_version = "3.14",
        architecture = "amd64",
        control = "//python:control",
    )

    python_archive(
        name = "python314_arm64",
        sha256 = "5bad659dc6d686b430f60104d53abfecb1cd93de37b8aaa112f10f0cea2cb655",
        strip_prefix = "python/",
        urls = ["https://github.com/astral-sh/python-build-standalone/releases/download/20260814/cpython-3.14.7+20260814-aarch64-unknown-linux-gnu-install_only.tar.gz"],
        version = "3.14.7+20260814",
        python_version = "3.14",
        architecture = "arm64",
        control = "//python:control",
    )

    python_archive(
        name = "python314_s390x",
        sha256 = "8ceecd7af302de3f6e6c4564dd671e4d1fa3a2a69f7d40075c75a2747d6ceacf",
        strip_prefix = "python/",
        urls = ["https://github.com/astral-sh/python-build-standalone/releases/download/20260814/cpython-3.14.7+20260814-s390x-unknown-linux-gnu-install_only.tar.gz"],
        version = "3.14.7+20260814",
        python_version = "3.14",
        architecture = "s390x",
        control = "//python:control",
    )

    python_archive(
        name = "python314_riscv64",
        sha256 = "9a85c88447db6ff01dfb6e6dfb27b2c856d48776d9ce8503ffd9ab2fa47960e6",
        strip_prefix = "python/",
        urls = ["https://github.com/astral-sh/python-build-standalone/releases/download/20260814/cpython-3.14.7+20260814-riscv64-unknown-linux-gnu-install_only.tar.gz"],
        version = "3.14.7+20260814",
        python_version = "3.14",
        architecture = "riscv64",
        control = "//python:control",
    )

    python_versions_repo(
        name = "python_versions",
        versions = {
            "3.13_amd64": "3.13.15",
            "3.13_arm64": "3.13.15",
            "3.13_s390x": "3.13.15",
            "3.13_riscv64": "3.13.15",
            "3.14_amd64": "3.14.7",
            "3.14_arm64": "3.14.7",
            "3.14_s390x": "3.14.7",
            "3.14_riscv64": "3.14.7",
        },
    )

    return module_ctx.extension_metadata(
        root_module_direct_deps = [
            "python_versions",
            "python313_amd64",
            "python313_arm64",
            "python313_s390x",
            "python313_riscv64",
            "python314_amd64",
            "python314_arm64",
            "python314_s390x",
            "python314_riscv64",
        ],
        root_module_direct_dev_deps = [],
    )

_archive = tag_class(attrs = {})

python = module_extension(
    implementation = _python_impl,
    tag_classes = {
        "archive": _archive,
    },
)
