name: Examples

on:
  pull_request:
    branches: [ 'main' ]

jobs:
  examples:
    name: Build and run examples
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: ./examples/test.sh
