timeout: 10800s  # 3 hours

options:
  machineType: E2_HIGHCPU_32
  logging: CLOUD_LOGGING_ONLY

artifacts:
  objects:
    location: 'gs://${_ARTIFACTS_GCS_}/logs'
    paths: ['.logs/*.log']

steps:
  - name: gcr.io/cloud-builders/bazel@sha256:05a39d8254df537c87bd6272f5c9f5ac8c77305c3e6dea9527c563da9016d0c3
    env:
      - PROJECT_ID=${PROJECT_ID}
      - COMMIT_SHA=${COMMIT_SHA}
      - REGISTRY=gcr.io
      - REMOTE_CACHE_GCS=${_REMOTE_CACHE_GCS_}
      - KEYLESS=keyless@${PROJECT_ID}.iam.gserviceaccount.com
    entrypoint: bash
    args: [".cloudbuild/release.sh"]
