name: Examples

on:
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: read

jobs:
  examples:
    name: Build and run examples
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - run: ./examples/test.sh
